import '../../models/character.dart';
import '../character/character_catalog.dart';
import 'clue_bank.dart';

/// Computer-player behaviour for the seats the host fills with studio players
///.
///
/// The host device is the single authority that drives these seats (see
/// [GameplayController]) and a studio player **never disconnects**. /// tunes them to a **moderate difficulty** so a table feels like real people
/// rather than a perfect machine:
///  * a clue-giver offers a gentle, varied one-word hint (never the word), and
///  * a guesser is *usually* right but sometimes needs a second try or misses,
///    so steals, reveals and varied scores happen naturally.
///
/// All behaviour is **deterministic for a given turn** (seeded by the word plus
/// the exchange count) so the single host driving the seat produces a stable
/// result even if it re-evaluates the same beat after a dropped request.
class AiPlayer {
  const AiPlayer._();

  /// Roughly how often a moderate-skill studio guesser lands the word on a
  /// given attempt. Tuned so AI seats score often enough that a table feels
  /// alive, while still missing enough for steals and reveals.
  static const double _guessAccuracy = 0.9;

  /// A one-word clue for [secretWord]. Uses a hand-picked hint for the words in
  /// the studio bank; falls back to a friendly generic nudge otherwise. The
  /// clue is never the word itself, so a human guesser still has to think. A
  /// bank word offers a few alternatives so repeat games don't feel scripted.
  /// Clues already spent on this word are passed as [avoid] so a stand-in never
  /// echoes the clue the other team just gave (Ronna, Aug 2026). Both clue
  /// tables are pooled to widen the choice, since a word can now need up to
  /// [MatchConfig.maxExchanges] different clues in a single round.
  static String clueFor(
    String secretWord, {
    int variant = 0,
    Iterable<String> avoid = const [],
  }) {
    final key = secretWord.trim().toLowerCase();
    final used = {for (final a in avoid) a.trim().toLowerCase()};
    // A word in the curated bank uses *only* its curated clues. Pooling the
    // legacy tables as well would let the placeholders back in — that is how
    // "Garden" ended up clued "Spot" and "Dog" clued "Wildlife". The legacy
    // tables are still there for a word that predates the bank, such as an
    // in-flight game holding an older deal.
    final curated = ClueBank.cluesFor(key);
    final pool = curated.isNotEmpty
        ? curated
        : <String>[...?_hints[key], ...?_semanticClues[key]];
    final options = <String>[];
    for (final c in pool) {
      if (_isBannedClue(c, key)) continue;
      final lower = c.trim().toLowerCase();
      if (options.any((o) => o.trim().toLowerCase() == lower)) continue;
      options.add(c);
    }
    // A word with no entry in either table still needs a clue per exchange.
    if (options.isEmpty) options.addAll(_genericNudges);
    // Rotate by variant so repeat games differ, then take the first clue this
    // word has not already used.
    final start = variant.abs() % options.length;
    for (var i = 0; i < options.length; i++) {
      final clue = options[(start + i) % options.length];
      if (!used.contains(clue.trim().toLowerCase())) return clue;
    }
    // Every known clue is spent — fall back to a generic nudge that is still new.
    for (final safe in _genericNudges) {
      if (!used.contains(safe.toLowerCase())) return safe;
    }
    return options[start];
  }

  /// Neutral nudges for a word with no curated clues, and for the rare word
  /// whose clues are all spent. Needs at least [MatchConfig.maxExchanges]
  /// entries so every exchange on one word can still offer something new.
  static const List<String> _genericNudges = [
    'Everyday', 'Familiar', 'Common', 'Ordinary', 'Household', 'Simple',
  ];

  /// A moderate-skill guess for [secretWord]. About [_guessAccuracy] of the
  /// time (deterministic per turn via [seed]) the studio player says the word;
  /// otherwise it offers a plausible, related-but-wrong guess so the other team
  /// gets a chance to steal — the "moderate difficulty" the spec calls for.
  ///
  /// It is given the [secretWord] only because it fills a seat (by design); the
  /// deliberate misses are what keep it fair rather than unbeatable.
  static String guessFor(String secretWord, {int seed = 0}) {
    final key = secretWord.trim().toLowerCase();
    if (key.isEmpty) return secretWord;
    // A cheap, stable hash of the word + turn seed → a 0..1 roll.
    var h = 2166136261 ^ seed;
    for (final c in key.codeUnits) {
      h = ((h ^ c) * 16777619) & 0x7fffffff;
    }
    final roll = (h % 1000) / 1000.0;
    if (roll < _guessAccuracy) return secretWord; // confident, correct guess
    return _plausibleMiss(key, h); // an honest wrong answer
  }

  /// A believable wrong guess, picked deterministically from [h] so the same
  /// turn always yields the same miss.
  ///
  /// Ronna (Aug 2026): "the clues and answers didn't make sense when stand-ins
  /// played". A miss used to come from [_missPool] regardless of the word, so
  /// the clue "Teapot" could be answered "Bicycle".
  ///
  /// A miss is now another answer from the same [ClueBank] family, which is both
  /// on-topic and a legal thing to say. Guessing one of the word's own *clues*
  /// would be a foul, so those are no longer used.
  static String _plausibleMiss(String key, int h) {
    final siblings = ClueBank.siblingsOf(key);
    if (siblings.isNotEmpty) return siblings[h % siblings.length];
    final related = <String>[
      ...?_semanticClues[key],
      ...?_hints[key],
    ].where((w) => w.trim().toLowerCase() != key).toList();
    if (related.isNotEmpty) return related[h % related.length];
    final pool = _missPool.where((w) => w.toLowerCase() != key).toList();
    if (pool.isEmpty) return 'Hmm';
    return pool[h % pool.length];
  }

  /// A small pool of common, on-theme words used for a studio player's
  /// occasional wrong guess so a miss reads as a real person thinking aloud.
  static const List<String> _missPool = [
    'Apple', 'Baker', 'Basket', 'Bicycle', 'Candle', 'Castle', 'Cookie',
    'Garden', 'Guitar', 'Horse', 'Jacket', 'Kitchen', 'Ladder', 'Lemon',
    'Market', 'Pillow', 'Plant', 'River', 'Sandwich', 'Window',
  ];

  /// Friendly first-name pool for studio seats (client demos + offline fill).
  static const fillNamePool = [
    'Sunny', 'Rosie', 'Buddy', 'Pearl', 'Gus', 'Mabel', 'Otis', 'Ada',
    'Walter', 'Rosa', 'Frank', 'Helen', 'Betty', 'Joe', 'Doris', 'Sam',
    'Nancy', 'Bill', 'Grace', 'Tom', 'Linda', 'Arthur', 'Margaret', 'Max',
  ];

  /// Deterministic unique names for empty seats in one game (mirrors SQL fill).
  static List<String> fillNamesForGame(
    String gameId, {
    required int count,
    Iterable<String> taken = const [],
  }) {
    final used = {
      for (final n in taken) n.trim().toLowerCase(),
    }..removeWhere((n) => n.isEmpty);
    final ranked = [...fillNamePool]..sort(
        (a, b) => _stableHash('$gameId:$a').compareTo(_stableHash('$gameId:$b')),
      );
    final out = <String>[];
    for (final name in ranked) {
      if (out.length >= count) break;
      final key = name.toLowerCase();
      if (used.contains(key)) continue;
      used.add(key);
      out.add(name);
    }
    var i = 1;
    while (out.length < count) {
      final fallback = 'Player$i';
      i++;
      if (used.contains(fallback.toLowerCase())) continue;
      used.add(fallback.toLowerCase());
      out.add(fallback);
    }
    return out;
  }

  static int _stableHash(String s) {
    var h = 2166136261;
    for (final c in s.codeUnits) {
      h = (h ^ c) * 16777619 & 0x7fffffff;
    }
    return h;
  }

  /// A deterministic, friendly character for a computer-filled seat, so studio
  /// players appear as real characters on the stage instead of a blank body.
  /// The same [seed] always yields the same look, so a player is consistent.
  static Character lookFor(String seed, String name) {
    return _lookFor(
      seed,
      name,
      usedHair: const {},
      usedGlasses: const {},
      usedHat: const {},
      usedOutfit: const {},
    );
  }

  /// Distinct looks for every AI seat in one match (video23: Rosie & Pearl
  /// shared the same hat + glasses). Hair, glasses, hat, and outfit stay unique
  /// across the roster while remaining stable for [salt].
  static Map<String, Character> looksForSeats(
    String salt,
    Iterable<({String role, String name})> seats,
  ) {
    final usedHair = <String>{};
    final usedGlasses = <String>{};
    final usedHat = <String>{};
    final usedOutfit = <String>{};
    final out = <String, Character>{};
    var i = 0;
    for (final seat in seats) {
      final c = _lookFor(
        '$salt:${seat.role}:${seat.name}:$i',
        seat.name,
        usedHair: usedHair,
        usedGlasses: usedGlasses,
        usedHat: usedHat,
        usedOutfit: usedOutfit,
      );
      if (c.hair != null) usedHair.add(c.hair!);
      usedGlasses.add(c.glasses ?? '__none__');
      usedHat.add(c.hat ?? '__none__');
      if (c.outfit != null) usedOutfit.add(c.outfit!);
      out[seat.role] = c;
      i++;
    }
    return out;
  }

  static Character _lookFor(
    String seed,
    String name, {
    required Set<String> usedHair,
    required Set<String> usedGlasses,
    required Set<String> usedHat,
    required Set<String> usedOutfit,
  }) {
    var h = 2166136261;
    for (final c in seed.codeUnits) {
      h = (h ^ c) * 16777619 & 0x7fffffff;
    }
    int pick(int n, int salt) =>
        n <= 0 ? 0 : ((h >> (salt % 24)) ^ (h * (salt + 1))) % n;

    final female = _isFemaleName(name) ?? (pick(2, 1) == 0);
    final base = female ? 'body-female' : 'body-male';

    String? pickAvoid(
      CharacterLayer layer,
      int salt, {
      required Set<String> used,
      bool allowNone = false,
      bool noneCounts = true,
      bool Function(String id)? keep,
    }) {
      var opts = CharacterCatalog.forLayer(layer, baseId: base)
          .where((o) => keep == null || keep(o.id))
          .toList();
      if (opts.isEmpty) return null;
      // Prefer unused ids; fall back to full list if exhausted.
      final fresh = opts.where((o) => !used.contains(o.id)).toList();
      if (fresh.isNotEmpty) opts = fresh;
      final noneOk = allowNone &&
          (!noneCounts || !used.contains('__none__'));
      final span = opts.length + (noneOk ? 1 : 0);
      final i = pick(span, salt);
      if (noneOk && i == opts.length) return null;
      return opts[i % opts.length].id;
    }

    final hair = pickAvoid(CharacterLayer.hair, 3, used: usedHair);
    final outfit = pickAvoid(CharacterLayer.outfit, 5, used: usedOutfit) ??
        CharacterCatalog.defaultOutfitFor(base);
    final glasses = pickAvoid(
      CharacterLayer.glasses,
      7,
      used: usedGlasses,
      allowNone: true,
    );
    final hat = pickAvoid(
      CharacterLayer.hat,
      13,
      used: usedHat,
      allowNone: true,
      keep: (id) {
        if (id.contains('knit')) return false;
        if (base == 'body-male' && id.contains('brim')) return false;
        return true;
      },
    );

    return Character(
      displayName: name,
      base: base,
      hair: hair,
      outfit: outfit,
      glasses: glasses,
      hat: hat,
    );
  }

  /// Known first-name gender hints for studio AI seats (null → use seed).
  static bool? _isFemaleName(String name) {
    final n = name.trim().toLowerCase();
    if (n.isEmpty) return null;
    const female = {
      'rosie', 'pearl', 'mabel', 'grace', 'sunny', 'betty', 'doris', 'helen',
      'margaret', 'nancy', 'susan', 'linda', 'barbara', 'patricia', 'jenny',
      'mary', 'anna', 'emma', 'olivia', 'sophia', 'ava', 'mia', 'amelia',
      'rosa',
    };
    const male = {
      'greg', 'walter', 'frank', 'harold', 'arthur', 'edward', 'robert',
      'james', 'john', 'william', 'michael', 'david', 'richard', 'thomas',
      'charles', 'joe', 'bill', 'bob', 'tom', 'sam', 'max', 'leo',
    };
    // Ambiguous nicknames leave gender to the seed.
    if (n == 'buddy' || n == 'pat' || n == 'alex' || n == 'chris') return null;
    if (female.contains(n)) return true;
    if (male.contains(n)) return false;
    if (n.endsWith('ette') || n.endsWith('elle')) return true;
    return null;
  }

  static bool _isBannedClue(String clue, String secret) {
    final c = clue.trim().toLowerCase();
    final s = secret.trim().toLowerCase();
    if (c.isEmpty || c == s) return true;
    if (c.startsWith('starts') || c.startsWith('ends')) return true;
    if (c.contains('letter')) return true;
    return false;
  }


  /// Semantic one-word clues for Ronna's Word Database v1 (no Starts/Ends/LetterCount).
  static const Map<String, List<String>> _semanticClues = {
    'accelerate': ['Speed', 'Faster', 'Pedal'],
    'accept': ['Receive', 'Take', 'Agree'],
    'accident': ['Crash', 'Mishap', 'Oops'],
    'account': ['Bank', 'Record', 'Ledger'],
    'accountant': ['Taxes', 'Numbers', 'Math'],
    'accuse': ['Blame', 'Charge', 'Point'],
    'actor': ['Stage', 'Movie', 'Role'],
    'actress': ['Stage', 'Movie', 'Role'],
    'add': ['Plus', 'Sum', 'Math'],
    'advise': ['Counsel', 'Suggest', 'Tip'],
    'afternoon': ['Daytime', 'Later', 'Noon'],
    'agree': ['Yes', 'Consent', 'Deal'],
    'alert': ['Warning', 'Awake', 'Ready'],
    'allow': ['Permit', 'Let', 'Okay'],
    'anchor': ['Ship', 'Hold', 'Heavy'],
    'anger': ['Mad', 'Rage', 'Upset'],
    'ankle': ['Foot', 'Joint', 'Step'],
    'anniversary': ['Yearly', 'Wedding', 'Date'],
    'announce': ['Declare', 'Tell', 'News'],
    'answer': ['Reply', 'Response', 'Solve'],
    'ant': ['Insect', 'Tiny', 'Colony'],
    'anthem': ['Song', 'National', 'Hymn'],
    'apologize': ['Sorry', 'Excuse', 'Regret'],
    'apple': ['Fruit', 'Orchard', 'Crunchy'],
    'approve': ['Okay', 'Permit', 'Pass'],
    'apricot': ['Fruit', 'Orange', 'Fuzzy'],
    'apron': ['Cook', 'Kitchen', 'Cloth'],
    'arch': ['Curve', 'Bridge', 'Bow'],
    'architect': ['Design', 'Building', 'Plans'],
    'arena': ['Stadium', 'Show', 'Crowd'],
    'argue': ['Debate', 'Fight', 'Disagree'],
    'arm': ['Limb', 'Sleeve', 'Hand'],
    'armor': ['Shield', 'Knight', 'Metal'],
    'army': ['Soldiers', 'Military', 'Troops'],
    'arrange': ['Organize', 'Order', 'Plan'],
    'arrive': ['Come', 'Reach', 'Land'],
    'arrow': ['Bow', 'Point', 'Direction'],
    'artist': ['Paint', 'Draw', 'Creative'],
    'ash': ['Fire', 'Gray', 'Dust'],
    'ask': ['Question', 'Request', 'Inquire'],
    'assemble': ['Gather', 'Build', 'Meet'],
    'assist': ['Help', 'Aid', 'Support'],
    'assume': ['Guess', 'Suppose', 'Presume'],
    'attack': ['Strike', 'Assault', 'Charge'],
    'attic': ['Upstairs', 'Roof', 'Storage'],
    'auditorium': ['Hall', 'Seats', 'Stage'],
    'aunt': ['Relative', 'Family', 'Sister'],
    'author': ['Writer', 'Book', 'Novel'],
    'autumn': ['Fall', 'Leaves', 'Season'],
    'axe': ['Chop', 'Wood', 'Blade'],
    'baby': ['Relative', 'Kin', 'People'],
    'back': ['Anatomy', 'Human', 'Flesh'],
    'backpack': ['Wear', 'Outfit', 'Fashion'],
    'badge': ['Wear', 'Outfit', 'Fashion'],
    'bag': ['Wear', 'Outfit', 'Fashion'],
    'bake': ['Make', 'Create', 'Build'],
    'baker': ['Career', 'Profession', 'Work'],
    'bakery': ['Location', 'Building', 'Spot'],
    'ball': ['Sport', 'Game', 'Play'],
    'balloon': ['Float', 'Party', 'Helium'],
    'banana': ['Snack', 'Meal', 'Tasty'],
    'bandage': ['Wound', 'Wrap', 'Firstaid'],
    'bank': ['Location', 'Building', 'Spot'],
    'banker': ['Career', 'Profession', 'Work'],
    'banner': ['Career', 'Profession', 'Work'],
    'bar': ['Pub', 'Rod', 'Counter'],
    'barber': ['Career', 'Profession', 'Work'],
    'bark': ['Dog', 'Tree', 'Rough'],
    'barn': ['Location', 'Building', 'Spot'],
    'barrel': ['Wood', 'Oil', 'Round'],
    'baseball': ['Sport', 'Game', 'Play'],
    'basement': ['Location', 'Building', 'Spot'],
    'basket': ['Carry', 'Wicker', 'Picnic'],
    'basketball': ['Sport', 'Game', 'Play'],
    'bat': ['Sport', 'Game', 'Play'],
    'bathroom': ['Location', 'Building', 'Spot'],
    'battery': ['Power', 'Charge', 'Energy'],
    'battle': ['Make', 'Create', 'Build'],
    'beach': ['Sand', 'Ocean', 'Shore'],
    'bean': ['Snack', 'Meal', 'Tasty'],
    'bear': ['Creature', 'Critter', 'Wildlife'],
    'beat': ['Rhythm', 'Win', 'Drum'],
    'bed': ['Sleep', 'Rest', 'Mattress'],
    'bedroom': ['Location', 'Building', 'Spot'],
    'bee': ['Honey', 'Buzz', 'Sting'],
    'beer': ['Snack', 'Meal', 'Tasty'],
    'beetle': ['Creature', 'Critter', 'Wildlife'],
    'begin': ['Think', 'Mind', 'Idea'],
    'believe': ['Think', 'Mind', 'Idea'],
    'belt': ['Waist', 'Buckle', 'Hold'],
    'bend': ['Curve', 'Flex', 'Angle'],
    'berry': ['Snack', 'Meal', 'Tasty'],
    'bicycle': ['Pedal', 'Wheels', 'Ride'],
    'bill': ['Money', 'Duck', 'Invoice'],
    'bird': ['Wings', 'Fly', 'Feather'],
    'birthday': ['Moment', 'Calendar', 'Season'],
    'bite': ['Teeth', 'Chew', 'Nip'],
    'black': ['Shade', 'Paint', 'Hue'],
    'blame': ['Think', 'Mind', 'Idea'],
    'blanket': ['Warm', 'Cover', 'Cozy'],
    'blend': ['Make', 'Create', 'Build'],
    'blender': ['Career', 'Profession', 'Work'],
    'blink': ['Think', 'Mind', 'Idea'],
    'blood': ['Anatomy', 'Human', 'Flesh'],
    'blue': ['Shade', 'Paint', 'Hue'],
    'blueberry': ['Snack', 'Meal', 'Tasty'],
    'board': ['Wood', 'Plank', 'Surf'],
    'boat': ['Water', 'Sail', 'Float'],
    'body': ['Anatomy', 'Human', 'Flesh'],
    'boil': ['Make', 'Create', 'Build'],
    'bolt': ['Tool', 'Utensil', 'Gear'],
    'bomb': ['Explode', 'Blast', 'Danger'],
    'bone': ['Skeleton', 'Dog', 'Calcium'],
    'book': ['Read', 'Pages', 'Story'],
    'bookstore': ['Location', 'Building', 'Spot'],
    'boot': ['Shoe', 'Mud', 'Winter'],
    'borrow': ['Think', 'Mind', 'Idea'],
    'bottle': ['Glass', 'Drink', 'Cap'],
    'bowl': ['Dish', 'Soup', 'Round'],
    'box': ['Package', 'Cardboard', 'Cube'],
    'boxing': ['Idea', 'Concept', 'Thought'],
    'boy': ['Relative', 'Kin', 'People'],
    'brain': ['Think', 'Mind', 'Smart'],
    'brake': ['Stop', 'Car', 'Pedal'],
    'bread': ['Loaf', 'Bakery', 'Toast'],
    'break': ['Idea', 'Concept', 'Thought'],
    'breeze': ['Outdoors', 'Natural', 'Earth'],
    'bridge': ['Cross', 'River', 'Span'],
    'broccoli': ['Snack', 'Meal', 'Tasty'],
    'bronze': ['Shade', 'Paint', 'Hue'],
    'broom': ['Sweep', 'Clean', 'Witch'],
    'brother': ['Relative', 'Kin', 'People'],
    'brown': ['Shade', 'Paint', 'Hue'],
    'brush': ['Hair', 'Paint', 'Teeth'],
    'bucket': ['Pail', 'Carry', 'Water'],
    'buckle': ['Thing', 'Item', 'Object'],
    'budget': ['Money', 'Plan', 'Spend'],
    'build': ['Make', 'Create', 'Bake'],
    'builder': ['Career', 'Profession', 'Work'],
    'bump': ['Hit', 'Lump', 'Road'],
    'burn': ['Fire', 'Hot', 'Flame'],
    'bury': ['Thing', 'Item', 'Object'],
    'bus': ['Ride', 'School', 'Transit'],
    'butcher': ['Career', 'Profession', 'Work'],
    'butter': ['Toast', 'Spread', 'Dairy'],
    'butterfly': ['Creature', 'Critter', 'Wildlife'],
    'button': ['Shirt', 'Push', 'Click'],
    'buy': ['Action', 'Doing', 'Verb'],
    'buzz': ['Person', 'Someone', 'People'],
    'cabbage': ['Snack', 'Meal', 'Tasty'],
    'cabinet': ['Household', 'Home', 'Indoor'],
    'cable': ['Wire', 'TV', 'Cord'],
    'cafe': ['Coffee', 'Sit', 'Lunch'],
    'cafeteria': ['Location', 'Building', 'Spot'],
    'cake': ['Birthday', 'Sweet', 'Frosting'],
    'call': ['Speak', 'Talk', 'Voice'],
    'calm': ['Emotion', 'Feeling', 'Mood'],
    'camera': ['Photo', 'Lens', 'Picture'],
    'camping': ['Thing', 'Item', 'Object'],
    'can': ['Household', 'Home', 'Indoor'],
    'candle': ['Wax', 'Flame', 'Glow'],
    'candy': ['Sweet', 'Sugar', 'Treat'],
    'cannon': ['Gun', 'Boom', 'War'],
    'canyon': ['Cliff', 'Valley', 'Deep'],
    'cap': ['Hat', 'Lid', 'Top'],
    'captain': ['Ship', 'Leader', 'Team'],
    'car': ['Drive', 'Road', 'Wheel'],
    'card': ['Deck', 'Paper', 'Birthday'],
    'carnival': ['Quality', 'Trait', 'Describe'],
    'carpenter': ['Career', 'Profession', 'Work'],
    'carpet': ['Floor', 'Rug', 'Soft'],
    'carrot': ['Orange', 'Vegetable', 'Rabbit'],
    'carry': ['Hold', 'Lift', 'Bring'],
    'carve': ['Make', 'Create', 'Build'],
    'cash': ['Money', 'Bills', 'Pay'],
    'cashier': ['Career', 'Profession', 'Work'],
    'castle': ['King', 'Tower', 'Stone'],
    'cat': ['Meow', 'Pet', 'Purr'],
    'catch': ['Grab', 'Ball', 'Receive'],
    'cave': ['Dark', 'Rock', 'Bat'],
    'ceiling': ['Roof', 'Above', 'Room'],
    'celebration': ['Idea', 'Concept', 'Topic'],
    'cell': ['Phone', 'Prison', 'Tiny'],
    'cello': ['Music', 'Tune', 'Song'],
    'cent': ['Penny', 'Money', 'Coin'],
    'ceremony': ['Action', 'Doing', 'Verb'],
    'certificate': ['Action', 'Doing', 'Change'],
    'chain': ['Link', 'Metal', 'Lock'],
    'chair': ['Sit', 'Seat', 'Furniture'],
    'change': ['Different', 'Coins', 'Alter'],
    'chapter': ['School', 'Study', 'Learn'],
    'charger': ['Career', 'Profession', 'Work'],
    'chase': ['Run', 'Follow', 'Pursue'],
    'chat': ['Talk', 'Converse', 'Speak'],
    'check': ['Verify', 'Bank', 'Mark'],
    'checker': ['Career', 'Profession', 'Work'],
    'cheek': ['Face', 'Blush', 'Kiss'],
    'cheese': ['Dairy', 'Mouse', 'Yellow'],
    'chef': ['Cook', 'Kitchen', 'Restaurant'],
    'cherry': ['Red', 'Fruit', 'Pie'],
    'chess': ['Board', 'King', 'Strategy'],
    'chest': ['Torso', 'Treasure', 'Box'],
    'chew': ['Bite', 'Gum', 'Mouth'],
    'chicken': ['Bird', 'Egg', 'Farm'],
    'child': ['Kid', 'Young', 'Play'],
    'chimney': ['Person', 'Someone', 'People'],
    'chin': ['Face', 'Jaw', 'Below'],
    'chirp': ['Person', 'Someone', 'People'],
    'chocolate': ['Sweet', 'Cocoa', 'Candy'],
    'choose': ['Think', 'Mind', 'Idea'],
    'chop': ['Make', 'Create', 'Build'],
    'chord': ['Place', 'Spot', 'Area'],
    'church': ['Worship', 'Steeple', 'Sunday'],
    'circle': ['Round', 'Ring', 'Shape'],
    'circus': ['Clown', 'Tent', 'Show'],
    'city': ['Town', 'Urban', 'Buildings'],
    'class': ['School', 'Group', 'Lesson'],
    'classroom': ['Location', 'Building', 'Spot'],
    'clay': ['Mud', 'Pottery', 'Sculpt'],
    'clean': ['Wash', 'Tidy', 'Soap'],
    'cleaner': ['Career', 'Profession', 'Work'],
    'clerk': ['Store', 'Office', 'Desk'],
    'cliff': ['Edge', 'Rock', 'High'],
    'climate': ['Action', 'Doing', 'Change'],
    'climb': ['Up', 'Mountain', 'Ladder'],
    'climbing': ['Idea', 'Concept', 'Thought'],
    'clinic': ['Quality', 'Trait', 'Describe'],
    'clock': ['Time', 'Tick', 'Hands'],
    'close': ['Shut', 'Near', 'End'],
    'closet': ['Location', 'Building', 'Spot'],
    'cloud': ['Sky', 'Rain', 'Fluffy'],
    'coach': ['Train', 'Sports', 'Teach'],
    'coast': ['Shore', 'Beach', 'Ocean'],
    'coat': ['Jacket', 'Warm', 'Wear'],
    'coconut': ['Palm', 'Tropical', 'Shell'],
    'coffee': ['Morning', 'Mug', 'Beans'],
    'coin': ['Money', 'Metal', 'Flip'],
    'college': ['School', 'Campus', 'Degree'],
    'collide': ['Idea', 'Concept', 'Thought'],
    'color': ['Hue', 'Paint', 'Shade'],
    'combine': ['Place', 'Spot', 'Area'],
    'comfort': ['Cozy', 'Ease', 'Soft'],
    'compete': ['Person', 'Someone', 'People'],
    'compromise': ['Action', 'Doing', 'Change'],
    'computer': ['Screen', 'Keyboard', 'Digital'],
    'concert': ['Music', 'Live', 'Show'],
    'condense': ['Idea', 'Concept', 'Thought'],
    'conductor': ['Career', 'Profession', 'Work'],
    'connect': ['Join', 'Link', 'Attach'],
    'continent': ['Place', 'Spot', 'Area'],
    'continue': ['Keep', 'Go', 'Proceed'],
    'convert': ['Change', 'Transform', 'Switch'],
    'cook': ['Kitchen', 'Chef', 'Food'],
    'cookie': ['Sweet', 'Bake', 'Jar'],
    'coop': ['Place', 'Spot', 'Area'],
    'copper': ['Career', 'Profession', 'Work'],
    'corn': ['Yellow', 'Cob', 'Farm'],
    'cost': ['Price', 'Expense', 'Pay'],
    'couch': ['Sofa', 'Sit', 'Living'],
    'council': ['Board', 'City', 'Group'],
    'counselor': ['Career', 'Profession', 'Work'],
    'count': ['Number', 'Tally', 'Math'],
    'country': ['Nation', 'Rural', 'Land'],
    'court': ['Judge', 'Tennis', 'Law'],
    'cousin': ['Relative', 'Family', 'Kin'],
    'cow': ['Milk', 'Farm', 'Moo'],
    'crab': ['Claws', 'Beach', 'Sideways'],
    'crash': ['Smash', 'Accident', 'Boom'],
    'crate': ['Action', 'Doing', 'Change'],
    'crawl': ['Baby', 'Slow', 'Knees'],
    'cream': ['Dairy', 'Whip', 'Lotion'],
    'create': ['Make', 'Invent', 'Build'],
    'credit': ['Card', 'Praise', 'Borrow'],
    'crime': ['Law', 'Theft', 'Illegal'],
    'criminal': ['Thief', 'Jail', 'Illegal'],
    'criticize': ['Action', 'Doing', 'Change'],
    'crop': ['Farm', 'Harvest', 'Field'],
    'crow': ['Place', 'Spot', 'Area'],
    'cruise': ['Ship', 'Vacation', 'Sail'],
    'crumble': ['Action', 'Doing', 'Verb'],
    'crush': ['Smash', 'Like', 'Squeeze'],
    'crutch': ['Person', 'Someone', 'People'],
    'cry': ['Tears', 'Sob', 'Sad'],
    'crystal': ['Clear', 'Glass', 'Gem'],
    'cucumber': ['Green', 'Salad', 'Vegetable'],
    'cup': ['Drink', 'Mug', 'Coffee'],
    'cupboard': ['Cabinet', 'Kitchen', 'Shelf'],
    'curtain': ['Window', 'Drape', 'Stage'],
    'cut': ['Slice', 'Scissors', 'Wound'],
    'cycling': ['Thing', 'Item', 'Object'],
    'dagger': ['Career', 'Profession', 'Work'],
    'dam': ['Action', 'Doing', 'Verb'],
    'dance': ['Music', 'Tune', 'Song'],
    'dancer': ['Career', 'Profession', 'Work'],
    'day': ['Moment', 'Calendar', 'Season'],
    'dean': ['Place', 'Spot', 'Area'],
    'debate': ['Action', 'Doing', 'Change'],
    'debt': ['Money', 'Finance', 'Cash'],
    'decide': ['Think', 'Mind', 'Idea'],
    'deer': ['Creature', 'Critter', 'Wildlife'],
    'defend': ['Person', 'Someone', 'People'],
    'degree': ['School', 'Study', 'Learn'],
    'demolish': ['Place', 'Spot', 'Area'],
    'dentist': ['Place', 'Spot', 'Area'],
    'deny': ['Speak', 'Talk', 'Voice'],
    'depart': ['Thing', 'Item', 'Object'],
    'depth': ['Place', 'Spot', 'Area'],
    'desert': ['Location', 'Building', 'Spot'],
    'design': ['Make', 'Create', 'Build'],
    'desk': ['Household', 'Home', 'Indoor'],
    'destroy': ['Place', 'Spot', 'Area'],
    'dew': ['Outdoors', 'Natural', 'Earth'],
    'diamond': ['Idea', 'Concept', 'Thought'],
    'dice': ['Thing', 'Item', 'Object'],
    'dig': ['Place', 'Spot', 'Area'],
    'diploma': ['School', 'Study', 'Learn'],
    'direct': ['Thing', 'Item', 'Object'],
    'director': ['Career', 'Profession', 'Work'],
    'dirt': ['Outdoors', 'Natural', 'Earth'],
    'disagree': ['Action', 'Doing', 'Verb'],
    'disaster': ['Place', 'Spot', 'Area'],
    'discover': ['Career', 'Profession', 'Work'],
    'discuss': ['Speak', 'Talk', 'Voice'],
    'disease': ['Person', 'Someone', 'People'],
    'dishwasher': ['Person', 'Someone', 'People'],
    'dislike': ['Action', 'Doing', 'Verb'],
    'dissolve': ['Place', 'Spot', 'Area'],
    'distance': ['Idea', 'Concept', 'Topic'],
    'dive': ['Water', 'Wet', 'Liquid'],
    'divide': ['Person', 'Someone', 'People'],
    'doctor': ['Career', 'Profession', 'Work'],
    'dog': ['Creature', 'Critter', 'Wildlife'],
    'doll': ['Idea', 'Concept', 'Thought'],
    'dollar': ['Money', 'Finance', 'Cash'],
    'dolphin': ['Creature', 'Critter', 'Wildlife'],
    'domino': ['Action', 'Doing', 'Verb'],
    'donut': ['Snack', 'Meal', 'Tasty'],
    'door': ['Household', 'Home', 'Indoor'],
    'doubt': ['Think', 'Mind', 'Idea'],
    'downgrade': ['Thing', 'Item', 'Object'],
    'drag': ['Person', 'Someone', 'People'],
    'dragon': ['Thing', 'Item', 'Object'],
    'draw': ['Make', 'Create', 'Build'],
    'drawer': ['Career', 'Profession', 'Work'],
    'dream': ['Think', 'Mind', 'Idea'],
    'dress': ['Wear', 'Outfit', 'Fashion'],
    'drill': ['Tool', 'Utensil', 'Gear'],
    'drink': ['Water', 'Wet', 'Liquid'],
    'drip': ['Water', 'Wet', 'Liquid'],
    'drive': ['Move', 'Go', 'Travel'],
    'driver': ['Career', 'Profession', 'Work'],
    'driveway': ['Thing', 'Item', 'Object'],
    'drop': ['Water', 'Wet', 'Liquid'],
    'drought': ['Water', 'Wet', 'Liquid'],
    'drum': ['Music', 'Tune', 'Song'],
    'duck': ['Creature', 'Critter', 'Wildlife'],
    'dust': ['Place', 'Spot', 'Area'],
    'eagle': ['Creature', 'Critter', 'Wildlife'],
    'ear': ['Anatomy', 'Human', 'Flesh'],
    'earn': ['Idea', 'Concept', 'Thought'],
    'earthquake': ['Idea', 'Concept', 'Thought'],
    'eat': ['Person', 'Someone', 'People'],
    'editor': ['Career', 'Profession', 'Work'],
    'egg': ['Snack', 'Meal', 'Tasty'],
    'elbow': ['Anatomy', 'Human', 'Flesh'],
    'election': ['Idea', 'Concept', 'Topic'],
    'electrician': ['Career', 'Profession', 'Work'],
    'elephant': ['Person', 'Someone', 'People'],
    'email': ['Thing', 'Item', 'Object'],
    'emerald': ['Thing', 'Item', 'Object'],
    'emergency': ['Person', 'Someone', 'People'],
    'emotion': ['Idea', 'Concept', 'Topic'],
    'end': ['Action', 'Doing', 'Verb'],
    'energy': ['Thing', 'Item', 'Object'],
    'engineer': ['Career', 'Profession', 'Work'],
    'enjoy': ['Person', 'Someone', 'People'],
    'enter': ['Career', 'Profession', 'Work'],
    'envelope': ['Household', 'Home', 'Indoor'],
    'evaporate': ['Action', 'Doing', 'Change'],
    'evening': ['Moment', 'Calendar', 'Season'],
    'evidence': ['Idea', 'Concept', 'Topic'],
    'exam': ['School', 'Study', 'Learn'],
    'exchange': ['Thing', 'Item', 'Object'],
    'exercise': ['Sport', 'Game', 'Play'],
    'exit': ['Move', 'Go', 'Travel'],
    'explain': ['Speak', 'Talk', 'Voice'],
    'explore': ['Idea', 'Concept', 'Thought'],
    'eye': ['Anatomy', 'Human', 'Flesh'],
    'factory': ['Thing', 'Item', 'Object'],
    'fair': ['Place', 'Spot', 'Area'],
    'fall': ['Moment', 'Calendar', 'Season'],
    'family': ['Relative', 'Kin', 'People'],
    'famine': ['Person', 'Someone', 'People'],
    'farm': ['Location', 'Building', 'Spot'],
    'farmer': ['Career', 'Profession', 'Work'],
    'father': ['Relative', 'Kin', 'People'],
    'fear': ['Emotion', 'Feeling', 'Mood'],
    'feel': ['Idea', 'Concept', 'Thought'],
    'feeling': ['Thing', 'Item', 'Object'],
    'fence': ['Idea', 'Concept', 'Topic'],
    'ferry': ['Location', 'Building', 'Spot'],
    'fertilizer': ['Place', 'Spot', 'Area'],
    'festival': ['Quality', 'Trait', 'Describe'],
    'field': ['Outdoors', 'Natural', 'Earth'],
    'fight': ['Thing', 'Item', 'Object'],
    'film': ['Person', 'Someone', 'People'],
    'find': ['Idea', 'Concept', 'Thought'],
    'finger': ['Anatomy', 'Human', 'Flesh'],
    'finish': ['Action', 'Doing', 'Verb'],
    'fire': ['Idea', 'Concept', 'Thought'],
    'firefighter': ['Career', 'Profession', 'Work'],
    'fireplace': ['Person', 'Someone', 'People'],
    'fish': ['Creature', 'Critter', 'Wildlife'],
    'fisherman': ['Idea', 'Concept', 'Thought'],
    'fishing': ['Person', 'Someone', 'People'],
    'fix': ['Make', 'Create', 'Build'],
    'flag': ['Thing', 'Item', 'Object'],
    'flame': ['Idea', 'Concept', 'Thought'],
    'flash': ['Action', 'Doing', 'Verb'],
    'float': ['Person', 'Someone', 'People'],
    'flood': ['Water', 'Wet', 'Liquid'],
    'floor': ['Household', 'Home', 'Indoor'],
    'florist': ['Action', 'Doing', 'Verb'],
    'flute': ['Music', 'Tune', 'Song'],
    'fly': ['Move', 'Go', 'Travel'],
    'fog': ['Outdoors', 'Natural', 'Earth'],
    'fold': ['Action', 'Doing', 'Verb'],
    'folder': ['Career', 'Profession', 'Work'],
    'follow': ['Move', 'Go', 'Travel'],
    'foot': ['Anatomy', 'Human', 'Flesh'],
    'football': ['Sport', 'Game', 'Play'],
    'forbid': ['Thing', 'Item', 'Object'],
    'force': ['Idea', 'Concept', 'Thought'],
    'forehead': ['Thing', 'Item', 'Object'],
    'forest': ['Location', 'Building', 'Spot'],
    'forget': ['Think', 'Mind', 'Idea'],
    'forgive': ['Quality', 'Trait', 'Describe'],
    'fork': ['Tool', 'Utensil', 'Gear'],
    'fountain': ['Place', 'Spot', 'Area'],
    'fox': ['Creature', 'Critter', 'Wildlife'],
    'frame': ['Place', 'Spot', 'Area'],
    'freeze': ['Action', 'Doing', 'Verb'],
    'fridge': ['Household', 'Home', 'Indoor'],
    'friend': ['Idea', 'Concept', 'Thought'],
    'frog': ['Creature', 'Critter', 'Wildlife'],
    'frost': ['Outdoors', 'Natural', 'Earth'],
    'frown': ['Action', 'Doing', 'Verb'],
    'fry': ['Idea', 'Concept', 'Thought'],
    'funeral': ['Quality', 'Trait', 'Describe'],
    'gale': ['Person', 'Someone', 'People'],
    'gallery': ['Idea', 'Concept', 'Thought'],
    'game': ['Sport', 'Play', 'Gym'],
    'garage': ['Location', 'Building', 'Spot'],
    'garden': ['Location', 'Building', 'Spot'],
    'gardener': ['Career', 'Profession', 'Work'],
    'garlic': ['Quality', 'Trait', 'Describe'],
    'gate': ['Action', 'Doing', 'Change'],
    'gather': ['Career', 'Profession', 'Work'],
    'giant': ['Action', 'Doing', 'Verb'],
    'giraffe': ['Person', 'Someone', 'People'],
    'girl': ['Relative', 'Kin', 'People'],
    'give': ['Quality', 'Trait', 'Describe'],
    'glacier': ['Outdoors', 'Natural', 'Earth'],
    'glance': ['Idea', 'Concept', 'Topic'],
    'glass': ['Place', 'Spot', 'Area'],
    'glide': ['Idea', 'Concept', 'Thought'],
    'glitter': ['Career', 'Profession', 'Work'],
    'glove': ['Wear', 'Outfit', 'Fashion'],
    'glow': ['Action', 'Doing', 'Verb'],
    'goal': ['Sport', 'Game', 'Play'],
    'goat': ['Creature', 'Critter', 'Wildlife'],
    'gold': ['Shade', 'Paint', 'Hue'],
    'golf': ['Sport', 'Game', 'Play'],
    'government': ['Idea', 'Concept', 'Topic'],
    'grab': ['Idea', 'Concept', 'Thought'],
    'grade': ['School', 'Study', 'Learn'],
    'grandfather': ['Career', 'Profession', 'Work'],
    'grandmother': ['Career', 'Profession', 'Work'],
    'grape': ['Snack', 'Meal', 'Tasty'],
    'gray': ['Shade', 'Paint', 'Hue'],
    'green': ['Shade', 'Paint', 'Hue'],
    'greet': ['Speak', 'Talk', 'Voice'],
    'grill': ['Place', 'Spot', 'Area'],
    'grow': ['Idea', 'Concept', 'Thought'],
    'growl': ['Thing', 'Item', 'Object'],
    'guard': ['Career', 'Profession', 'Work'],
    'guess': ['Think', 'Mind', 'Idea'],
    'guest': ['Idea', 'Concept', 'Thought'],
    'guide': ['Action', 'Doing', 'Verb'],
    'guilt': ['Emotion', 'Feeling', 'Mood'],
    'guitar': ['Music', 'Tune', 'Song'],
    'gun': ['Thing', 'Item', 'Object'],
    'gym': ['Sport', 'Game', 'Play'],
    'hair': ['Anatomy', 'Human', 'Flesh'],
    'hallway': ['Location', 'Building', 'Spot'],
    'hammer': ['Career', 'Profession', 'Work'],
    'hand': ['Anatomy', 'Human', 'Flesh'],
    'harp': ['Music', 'Tune', 'Song'],
    'harvest': ['Thing', 'Item', 'Object'],
    'hat': ['Wear', 'Outfit', 'Fashion'],
    'hate': ['Emotion', 'Feeling', 'Mood'],
    'hawk': ['Creature', 'Critter', 'Wildlife'],
    'head': ['Anatomy', 'Human', 'Flesh'],
    'headphone': ['Music', 'Tune', 'Song'],
    'health': ['Thing', 'Item', 'Object'],
    'hear': ['Action', 'Doing', 'Verb'],
    'heart': ['Anatomy', 'Human', 'Flesh'],
    'height': ['Place', 'Spot', 'Area'],
    'helicopter': ['Transport', 'Travel', 'Ride'],
    'helmet': ['Wear', 'Outfit', 'Fashion'],
    'help': ['Thing', 'Item', 'Object'],
    'highway': ['Location', 'Building', 'Spot'],
    'hiking': ['Person', 'Someone', 'People'],
    'hill': ['Outdoors', 'Natural', 'Earth'],
    'hip': ['Anatomy', 'Human', 'Flesh'],
    'hiss': ['Person', 'Someone', 'People'],
    'hit': ['Thing', 'Item', 'Object'],
    'hockey': ['Sport', 'Game', 'Play'],
    'hold': ['Place', 'Spot', 'Area'],
    'holiday': ['Moment', 'Calendar', 'Season'],
    'home': ['Thing', 'Item', 'Object'],
    'homework': ['School', 'Study', 'Learn'],
    'honey': ['Snack', 'Meal', 'Tasty'],
    'hook': ['Tool', 'Utensil', 'Gear'],
    'hoot': ['Idea', 'Concept', 'Thought'],
    'hop': ['Idea', 'Concept', 'Thought'],
    'hope': ['Emotion', 'Feeling', 'Mood'],
    'horn': ['Person', 'Someone', 'People'],
    'horse': ['Creature', 'Critter', 'Wildlife'],
    'hospital': ['Location', 'Building', 'Spot'],
    'hotel': ['Location', 'Building', 'Spot'],
    'hour': ['Moment', 'Calendar', 'Season'],
    'house': ['Location', 'Building', 'Spot'],
    'hum': ['Music', 'Tune', 'Song'],
    'hunting': ['Thing', 'Item', 'Object'],
    'hurricane': ['Action', 'Doing', 'Verb'],
    'husband': ['Relative', 'Kin', 'People'],
    'ice': ['Outdoors', 'Natural', 'Earth'],
    'icecream': ['Snack', 'Meal', 'Tasty'],
    'idea': ['Place', 'Spot', 'Area'],
    'illness': ['Idea', 'Concept', 'Topic'],
    'imagine': ['Think', 'Mind', 'Idea'],
    'improve': ['Thing', 'Item', 'Object'],
    'income': ['Thing', 'Item', 'Object'],
    'increase': ['Idea', 'Concept', 'Thought'],
    'inform': ['Action', 'Doing', 'Verb'],
    'instrument': ['Idea', 'Concept', 'Topic'],
    'interest': ['Money', 'Finance', 'Cash'],
    'introduce': ['Place', 'Spot', 'Area'],
    'invent': ['Make', 'Create', 'Build'],
    'iron': ['Thing', 'Item', 'Object'],
    'irrigation': ['Idea', 'Concept', 'Topic'],
    'island': ['Location', 'Building', 'Spot'],
    'jacket': ['Wear', 'Outfit', 'Fashion'],
    'jail': ['Action', 'Doing', 'Verb'],
    'jam': ['Snack', 'Meal', 'Tasty'],
    'janitor': ['Career', 'Profession', 'Work'],
    'jar': ['Idea', 'Concept', 'Thought'],
    'jeweler': ['Career', 'Profession', 'Work'],
    'join': ['Idea', 'Concept', 'Thought'],
    'joke': ['Thing', 'Item', 'Object'],
    'journalist': ['Person', 'Someone', 'People'],
    'joy': ['Emotion', 'Feeling', 'Mood'],
    'judge': ['Career', 'Profession', 'Work'],
    'juice': ['Snack', 'Meal', 'Tasty'],
    'jump': ['Sport', 'Game', 'Play'],
    'jumping': ['Idea', 'Concept', 'Thought'],
    'jungle': ['Location', 'Building', 'Spot'],
    'kangaroo': ['Thing', 'Item', 'Object'],
    'kettle': ['Tool', 'Utensil', 'Gear'],
    'key': ['Household', 'Home', 'Indoor'],
    'keyboard': ['Person', 'Someone', 'People'],
    'kick': ['Sport', 'Game', 'Play'],
    'kidney': ['Person', 'Someone', 'People'],
    'king': ['Thing', 'Item', 'Object'],
    'kitchen': ['Location', 'Building', 'Spot'],
    'kite': ['Person', 'Someone', 'People'],
    'knee': ['Anatomy', 'Human', 'Flesh'],
    'knife': ['Tool', 'Utensil', 'Gear'],
    'knight': ['Thing', 'Item', 'Object'],
    'knock': ['Person', 'Someone', 'People'],
    'know': ['Think', 'Mind', 'Idea'],
    'laboratory': ['Idea', 'Concept', 'Thought'],
    'ladder': ['Tool', 'Utensil', 'Gear'],
    'ladybug': ['Creature', 'Critter', 'Wildlife'],
    'lake': ['Outdoors', 'Natural', 'Earth'],
    'lamp': ['Household', 'Home', 'Indoor'],
    'land': ['Location', 'Building', 'Spot'],
    'laptop': ['Action', 'Doing', 'Verb'],
    'laugh': ['Person', 'Someone', 'People'],
    'law': ['Person', 'Someone', 'People'],
    'lawyer': ['Career', 'Profession', 'Work'],
    'lead': ['Move', 'Go', 'Travel'],
    'learn': ['Think', 'Mind', 'Idea'],
    'leave': ['Move', 'Go', 'Travel'],
    'lecture': ['Action', 'Doing', 'Verb'],
    'leg': ['Anatomy', 'Human', 'Flesh'],
    'lemon': ['Snack', 'Meal', 'Tasty'],
    'lemonade': ['Idea', 'Concept', 'Thought'],
    'lend': ['Person', 'Someone', 'People'],
    'length': ['Idea', 'Concept', 'Thought'],
    'lesson': ['School', 'Study', 'Learn'],
    'letter': ['School', 'Study', 'Learn'],
    'lettuce': ['Place', 'Spot', 'Area'],
    'librarian': ['Place', 'Spot', 'Area'],
    'library': ['Location', 'Building', 'Spot'],
    'lie': ['Person', 'Someone', 'People'],
    'lift': ['Move', 'Go', 'Travel'],
    'lightning': ['Outdoors', 'Natural', 'Earth'],
    'like': ['Action', 'Doing', 'Verb'],
    'lime': ['Place', 'Spot', 'Area'],
    'link': ['Thing', 'Item', 'Object'],
    'lion': ['Creature', 'Critter', 'Wildlife'],
    'lip': ['Anatomy', 'Human', 'Flesh'],
    'listen': ['Thing', 'Item', 'Object'],
    'liver': ['Anatomy', 'Human', 'Flesh'],
    'loan': ['Money', 'Finance', 'Cash'],
    'lobster': ['Creature', 'Critter', 'Wildlife'],
    'lock': ['Household', 'Home', 'Indoor'],
    'locksmith': ['Person', 'Someone', 'People'],
    'look': ['Idea', 'Concept', 'Thought'],
    'lose': ['Sport', 'Game', 'Play'],
    'loss': ['Money', 'Finance', 'Cash'],
    'love': ['Emotion', 'Feeling', 'Mood'],
    'lung': ['Anatomy', 'Human', 'Flesh'],
    'magazine': ['Person', 'Someone', 'People'],
    'make': ['Create', 'Build', 'Chop'],
    'mall': ['Location', 'Building', 'Spot'],
    'man': ['Action', 'Doing', 'Verb'],
    'manager': ['Career', 'Profession', 'Work'],
    'mango': ['Thing', 'Item', 'Object'],
    'map': ['Place', 'Spot', 'Area'],
    'marble': ['Idea', 'Concept', 'Thought'],
    'market': ['Location', 'Building', 'Spot'],
    'mayor': ['Career', 'Profession', 'Work'],
    'maze': ['Person', 'Someone', 'People'],
    'meadow': ['Outdoors', 'Natural', 'Earth'],
    'measure': ['Make', 'Create', 'Build'],
    'mechanic': ['Career', 'Profession', 'Work'],
    'medal': ['Sport', 'Game', 'Play'],
    'medicine': ['Thing', 'Item', 'Object'],
    'meet': ['Idea', 'Concept', 'Thought'],
    'melody': ['Music', 'Tune', 'Song'],
    'melon': ['Person', 'Someone', 'People'],
    'melt': ['Person', 'Someone', 'People'],
    'memory': ['Thing', 'Item', 'Object'],
    'mention': ['Speak', 'Talk', 'Voice'],
    'mentor': ['Career', 'Profession', 'Work'],
    'meow': ['Thing', 'Item', 'Object'],
    'merge': ['Place', 'Spot', 'Area'],
    'message': ['Action', 'Doing', 'Verb'],
    'milk': ['Snack', 'Meal', 'Tasty'],
    'milkshake': ['Place', 'Spot', 'Area'],
    'mine': ['Thing', 'Item', 'Object'],
    'miner': ['Career', 'Profession', 'Work'],
    'minister': ['Career', 'Profession', 'Work'],
    'minute': ['Moment', 'Calendar', 'Season'],
    'mirror': ['Household', 'Home', 'Indoor'],
    'missile': ['Place', 'Spot', 'Area'],
    'mist': ['Outdoors', 'Natural', 'Earth'],
    'mitten': ['Idea', 'Concept', 'Thought'],
    'mix': ['Make', 'Create', 'Build'],
    'mock': ['Action', 'Doing', 'Verb'],
    'mold': ['Place', 'Spot', 'Area'],
    'money': ['Finance', 'Cash', 'Account'],
    'monkey': ['Person', 'Someone', 'People'],
    'month': ['Moment', 'Calendar', 'Season'],
    'monument': ['Idea', 'Concept', 'Topic'],
    'moon': ['Outdoors', 'Natural', 'Earth'],
    'mop': ['Tool', 'Utensil', 'Gear'],
    'morning': ['Moment', 'Calendar', 'Season'],
    'mosque': ['Location', 'Building', 'Spot'],
    'mother': ['Relative', 'Kin', 'People'],
    'motorcycle': ['Transport', 'Travel', 'Ride'],
    'mountain': ['Outdoors', 'Natural', 'Earth'],
    'mouse': ['Creature', 'Critter', 'Wildlife'],
    'mouth': ['Anatomy', 'Human', 'Flesh'],
    'movie': ['Person', 'Someone', 'People'],
    'mow': ['Person', 'Someone', 'People'],
    'mud': ['Outdoors', 'Natural', 'Earth'],
    'muffin': ['Snack', 'Meal', 'Tasty'],
    'mug': ['Household', 'Home', 'Indoor'],
    'multiply': ['Action', 'Doing', 'Verb'],
    'muscle': ['Anatomy', 'Human', 'Flesh'],
    'museum': ['Location', 'Building', 'Spot'],
    'mushroom': ['Location', 'Building', 'Spot'],
    'music': ['Tune', 'Song', 'Saxophone'],
    'musician': ['Idea', 'Concept', 'Thought'],
    'nail': ['Anatomy', 'Human', 'Flesh'],
    'napkin': ['Action', 'Doing', 'Verb'],
    'nation': ['Idea', 'Concept', 'Topic'],
    'navigate': ['Action', 'Doing', 'Change'],
    'navy': ['Action', 'Doing', 'Verb'],
    'neck': ['Anatomy', 'Human', 'Flesh'],
    'need': ['Idea', 'Concept', 'Thought'],
    'needle': ['Tool', 'Utensil', 'Gear'],
    'negotiate': ['Action', 'Doing', 'Change'],
    'neighbor': ['Relative', 'Kin', 'People'],
    'net': ['Idea', 'Concept', 'Thought'],
    'newspaper': ['Action', 'Doing', 'Verb'],
    'night': ['Moment', 'Calendar', 'Season'],
    'nose': ['Anatomy', 'Human', 'Flesh'],
    'note': ['Music', 'Tune', 'Song'],
    'notebook': ['Household', 'Home', 'Indoor'],
    'notify': ['Action', 'Doing', 'Change'],
    'novel': ['Place', 'Spot', 'Area'],
    'number': ['Person', 'Someone', 'People'],
    'nurse': ['Career', 'Profession', 'Work'],
    'ocean': ['Outdoors', 'Natural', 'Earth'],
    'octopus': ['Action', 'Doing', 'Verb'],
    'offer': ['Career', 'Profession', 'Work'],
    'office': ['Location', 'Building', 'Spot'],
    'officer': ['Career', 'Profession', 'Work'],
    'onion': ['Snack', 'Meal', 'Tasty'],
    'open': ['Person', 'Someone', 'People'],
    'orange': ['Shade', 'Paint', 'Hue'],
    'organize': ['Make', 'Create', 'Build'],
    'oval': ['Quality', 'Trait', 'Describe'],
    'oven': ['Household', 'Home', 'Indoor'],
    'owl': ['Creature', 'Critter', 'Wildlife'],
    'pack': ['Thing', 'Item', 'Object'],
    'paddle': ['Place', 'Spot', 'Area'],
    'page': ['Place', 'Spot', 'Area'],
    'paint': ['Tool', 'Utensil', 'Gear'],
    'painter': ['Career', 'Profession', 'Work'],
    'painting': ['Place', 'Spot', 'Area'],
    'pajama': ['Place', 'Spot', 'Area'],
    'palace': ['Location', 'Building', 'Spot'],
    'pan': ['Household', 'Home', 'Indoor'],
    'pancake': ['Snack', 'Meal', 'Tasty'],
    'pants': ['Wear', 'Outfit', 'Fashion'],
    'paper': ['Action', 'Doing', 'Verb'],
    'parade': ['Action', 'Doing', 'Verb'],
    'paragraph': ['Thing', 'Item', 'Object'],
    'parent': ['Relative', 'Kin', 'People'],
    'park': ['Location', 'Building', 'Spot'],
    'parliament': ['Idea', 'Concept', 'Topic'],
    'parrot': ['Person', 'Someone', 'People'],
    'party': ['Thing', 'Item', 'Object'],
    'pasta': ['Snack', 'Meal', 'Tasty'],
    'pasture': ['Idea', 'Concept', 'Thought'],
    'path': ['Location', 'Building', 'Spot'],
    'patient': ['Idea', 'Concept', 'Thought'],
    'pay': ['Money', 'Finance', 'Cash'],
    'pea': ['Thing', 'Item', 'Object'],
    'peach': ['Snack', 'Meal', 'Tasty'],
    'pear': ['Person', 'Someone', 'People'],
    'pearl': ['Idea', 'Concept', 'Thought'],
    'pen': ['Place', 'Spot', 'Area'],
    'pencil': ['Tool', 'Utensil', 'Gear'],
    'penguin': ['Creature', 'Critter', 'Wildlife'],
    'pepper': ['Snack', 'Meal', 'Tasty'],
    'permit': ['Idea', 'Concept', 'Thought'],
    'pharmacist': ['Place', 'Spot', 'Area'],
    'phone': ['Household', 'Home', 'Indoor'],
    'photograph': ['Person', 'Someone', 'People'],
    'photographer': ['Career', 'Profession', 'Work'],
    'piano': ['Music', 'Tune', 'Song'],
    'pick': ['Place', 'Spot', 'Area'],
    'picture': ['Person', 'Someone', 'People'],
    'pie': ['Snack', 'Meal', 'Tasty'],
    'pig': ['Creature', 'Critter', 'Wildlife'],
    'pill': ['Place', 'Spot', 'Area'],
    'pillow': ['Soft', 'Bed', 'Sleep'],
    'pilot': ['Career', 'Profession', 'Work'],
    'pin': ['Tool', 'Utensil', 'Gear'],
    'pineapple': ['Place', 'Spot', 'Area'],
    'pink': ['Color', 'Blush', 'Rose'],
    'pizza': ['Snack', 'Meal', 'Tasty'],
    'plan': ['Make', 'Create', 'Build'],
    'plane': ['Transport', 'Travel', 'Ride'],
    'plant': ['Place', 'Spot', 'Area'],
    'plate': ['Household', 'Home', 'Indoor'],
    'play': ['Place', 'Spot', 'Area'],
    'playground': ['Place', 'Spot', 'Area'],
    'plow': ['Tool', 'Utensil', 'Gear'],
    'pluck': ['Place', 'Spot', 'Area'],
    'plum': ['Snack', 'Meal', 'Tasty'],
    'plumber': ['Career', 'Profession', 'Work'],
    'poem': ['Place', 'Spot', 'Area'],
    'poet': ['Thing', 'Item', 'Object'],
    'police': ['Career', 'Profession', 'Work'],
    'polish': ['Thing', 'Item', 'Object'],
    'porch': ['Location', 'Building', 'Spot'],
    'postcard': ['Household', 'Home', 'Indoor'],
    'poster': ['Career', 'Profession', 'Work'],
    'pot': ['Household', 'Home', 'Indoor'],
    'potato': ['Snack', 'Meal', 'Tasty'],
    'pour': ['Water', 'Wet', 'Liquid'],
    'power': ['Idea', 'Concept', 'Thought'],
    'practice': ['Place', 'Spot', 'Area'],
    'praise': ['Speak', 'Talk', 'Voice'],
    'prefer': ['Career', 'Profession', 'Work'],
    'prepare': ['Make', 'Create', 'Build'],
    'president': ['Person', 'Someone', 'People'],
    'prevent': ['Idea', 'Concept', 'Thought'],
    'price': ['Money', 'Finance', 'Cash'],
    'pride': ['Emotion', 'Feeling', 'Mood'],
    'prince': ['Action', 'Doing', 'Verb'],
    'princess': ['Action', 'Doing', 'Verb'],
    'principal': ['Career', 'Profession', 'Work'],
    'print': ['Idea', 'Concept', 'Thought'],
    'printer': ['Career', 'Profession', 'Work'],
    'prison': ['Idea', 'Concept', 'Thought'],
    'professor': ['Career', 'Profession', 'Work'],
    'profit': ['Money', 'Finance', 'Cash'],
    'protect': ['Person', 'Someone', 'People'],
    'pull': ['Move', 'Go', 'Travel'],
    'pumpkin': ['Snack', 'Meal', 'Tasty'],
    'punch': ['Idea', 'Concept', 'Thought'],
    'purple': ['Shade', 'Paint', 'Hue'],
    'purse': ['Money', 'Finance', 'Cash'],
    'push': ['Move', 'Go', 'Travel'],
    'puzzle': ['Household', 'Home', 'Indoor'],
    'quarry': ['Action', 'Doing', 'Verb'],
    'queen': ['Idea', 'Concept', 'Thought'],
    'rabbit': ['Creature', 'Critter', 'Wildlife'],
    'race': ['Sport', 'Game', 'Play'],
    'racket': ['Person', 'Someone', 'People'],
    'radio': ['Household', 'Home', 'Indoor'],
    'rain': ['Outdoors', 'Natural', 'Earth'],
    'rainbow': ['Outdoors', 'Natural', 'Earth'],
    'rake': ['Tool', 'Utensil', 'Gear'],
    'ranch': ['Person', 'Someone', 'People'],
    'raspberry': ['Snack', 'Meal', 'Tasty'],
    'rat': ['Idea', 'Concept', 'Thought'],
    'read': ['Idea', 'Concept', 'Thought'],
    'reap': ['Person', 'Someone', 'People'],
    'receipt': ['Money', 'Finance', 'Cash'],
    'receive': ['Quality', 'Trait', 'Describe'],
    'recommend': ['Person', 'Someone', 'People'],
    'rectangle': ['Person', 'Someone', 'People'],
    'red': ['Shade', 'Paint', 'Hue'],
    'reduce': ['Idea', 'Concept', 'Thought'],
    'referee': ['Person', 'Someone', 'People'],
    'refuse': ['Thing', 'Item', 'Object'],
    'reject': ['Idea', 'Concept', 'Thought'],
    'relax': ['Thing', 'Item', 'Object'],
    'remember': ['Career', 'Profession', 'Work'],
    'remind': ['Person', 'Someone', 'People'],
    'repair': ['Make', 'Create', 'Build'],
    'report': ['Speak', 'Talk', 'Voice'],
    'reporter': ['Career', 'Profession', 'Work'],
    'rest': ['Action', 'Doing', 'Verb'],
    'restaurant': ['Location', 'Building', 'Spot'],
    'return': ['Move', 'Go', 'Travel'],
    'rhythm': ['Music', 'Tune', 'Song'],
    'ribbon': ['Wear', 'Outfit', 'Fashion'],
    'rice': ['Snack', 'Meal', 'Tasty'],
    'ride': ['Move', 'Go', 'Travel'],
    'rip': ['Action', 'Doing', 'Verb'],
    'rise': ['Move', 'Go', 'Travel'],
    'river': ['Career', 'Profession', 'Work'],
    'road': ['Location', 'Building', 'Spot'],
    'roar': ['Action', 'Doing', 'Verb'],
    'roast': ['Place', 'Spot', 'Area'],
    'robe': ['Wear', 'Outfit', 'Fashion'],
    'robot': ['Thing', 'Item', 'Object'],
    'rock': ['Outdoors', 'Natural', 'Earth'],
    'rocket': ['Transport', 'Travel', 'Ride'],
    'roll': ['Action', 'Doing', 'Verb'],
    'roof': ['Place', 'Spot', 'Area'],
    'room': ['Location', 'Building', 'Spot'],
    'rope': ['Tool', 'Utensil', 'Gear'],
    'rotate': ['Action', 'Doing', 'Change'],
    'row': ['Person', 'Someone', 'People'],
    'rowing': ['Idea', 'Concept', 'Thought'],
    'ruby': ['Thing', 'Item', 'Object'],
    'rug': ['Household', 'Home', 'Indoor'],
    'rule': ['Thing', 'Item', 'Object'],
    'run': ['Sport', 'Game', 'Play'],
    'running': ['Person', 'Someone', 'People'],
    'sadness': ['Idea', 'Concept', 'Topic'],
    'sail': ['Thing', 'Item', 'Object'],
    'sailing': ['Place', 'Spot', 'Area'],
    'sailor': ['Career', 'Profession', 'Work'],
    'salad': ['Snack', 'Meal', 'Tasty'],
    'salary': ['Money', 'Finance', 'Cash'],
    'salesman': ['Idea', 'Concept', 'Thought'],
    'salt': ['Snack', 'Meal', 'Tasty'],
    'sand': ['Outdoors', 'Natural', 'Earth'],
    'sandwich': ['Snack', 'Meal', 'Tasty'],
    'sapphire': ['Thing', 'Item', 'Object'],
    'sauce': ['Snack', 'Meal', 'Tasty'],
    'save': ['Action', 'Doing', 'Verb'],
    'saw': ['Tool', 'Utensil', 'Gear'],
    'saxophone': ['Music', 'Tune', 'Song'],
    'say': ['Speak', 'Talk', 'Voice'],
    'scanner': ['Career', 'Profession', 'Work'],
    'scarf': ['Wear', 'Outfit', 'Fashion'],
    'scholarship': ['Person', 'Someone', 'People'],
    'school': ['Location', 'Building', 'Spot'],
    'scientist': ['Career', 'Profession', 'Work'],
    'scooter': ['Career', 'Profession', 'Work'],
    'screen': ['Thing', 'Item', 'Object'],
    'screw': ['Household', 'Home', 'Indoor'],
    'scrub': ['Place', 'Spot', 'Area'],
    'sculpt': ['Idea', 'Concept', 'Thought'],
    'sea': ['Place', 'Spot', 'Area'],
    'search': ['Thing', 'Item', 'Object'],
    'season': ['Moment', 'Calendar', 'Birthday'],
    'second': ['Moment', 'Calendar', 'Season'],
    'see': ['Idea', 'Concept', 'Thought'],
    'seed': ['Outdoors', 'Natural', 'Earth'],
    'sell': ['Idea', 'Concept', 'Thought'],
    'senator': ['Person', 'Someone', 'People'],
    'send': ['Action', 'Doing', 'Verb'],
    'sentence': ['Idea', 'Concept', 'Topic'],
    'separate': ['Action', 'Doing', 'Change'],
    'shade': ['Idea', 'Concept', 'Thought'],
    'shake': ['Person', 'Someone', 'People'],
    'shame': ['Emotion', 'Feeling', 'Mood'],
    'shape': ['Person', 'Someone', 'People'],
    'shark': ['Creature', 'Critter', 'Wildlife'],
    'sheep': ['Creature', 'Critter', 'Wildlife'],
    'sheet': ['Household', 'Home', 'Indoor'],
    'shelf': ['Household', 'Home', 'Indoor'],
    'shield': ['Place', 'Spot', 'Area'],
    'shine': ['Thing', 'Item', 'Object'],
    'ship': ['Transport', 'Travel', 'Ride'],
    'shirt': ['Wear', 'Outfit', 'Fashion'],
    'shoe': ['Wear', 'Outfit', 'Fashion'],
    'shop': ['Location', 'Building', 'Spot'],
    'shore': ['Thing', 'Item', 'Object'],
    'shoulder': ['Anatomy', 'Human', 'Flesh'],
    'shout': ['Speak', 'Talk', 'Voice'],
    'shove': ['Person', 'Someone', 'People'],
    'shovel': ['Tool', 'Utensil', 'Gear'],
    'show': ['Person', 'Someone', 'People'],
    'shred': ['Person', 'Someone', 'People'],
    'shrimp': ['Person', 'Someone', 'People'],
    'sibling': ['Person', 'Someone', 'People'],
    'sidewalk': ['Location', 'Building', 'Spot'],
    'sight': ['Place', 'Spot', 'Area'],
    'signal': ['Quality', 'Trait', 'Describe'],
    'silo': ['Person', 'Someone', 'People'],
    'silver': ['Shade', 'Paint', 'Hue'],
    'sing': ['Place', 'Spot', 'Area'],
    'singer': ['Career', 'Profession', 'Work'],
    'sink': ['Household', 'Home', 'Indoor'],
    'sister': ['Relative', 'Kin', 'People'],
    'sit': ['Action', 'Doing', 'Verb'],
    'size': ['Action', 'Doing', 'Change'],
    'skating': ['Place', 'Spot', 'Area'],
    'sketch': ['Idea', 'Concept', 'Thought'],
    'skiing': ['Thing', 'Item', 'Object'],
    'skin': ['Anatomy', 'Human', 'Flesh'],
    'skip': ['Person', 'Someone', 'People'],
    'skirt': ['Wear', 'Outfit', 'Fashion'],
    'sky': ['Outdoors', 'Natural', 'Earth'],
    'slap': ['Idea', 'Concept', 'Thought'],
    'sled': ['Transport', 'Travel', 'Ride'],
    'sleep': ['Idea', 'Concept', 'Thought'],
    'sleigh': ['Action', 'Doing', 'Verb'],
    'slice': ['Make', 'Create', 'Build'],
    'slide': ['Person', 'Someone', 'People'],
    'slip': ['Thing', 'Item', 'Object'],
    'smell': ['Action', 'Doing', 'Verb'],
    'smile': ['Place', 'Spot', 'Area'],
    'smoke': ['Place', 'Spot', 'Area'],
    'snail': ['Thing', 'Item', 'Object'],
    'snake': ['Creature', 'Critter', 'Wildlife'],
    'sniff': ['Person', 'Someone', 'People'],
    'snow': ['Outdoors', 'Natural', 'Earth'],
    'soar': ['Idea', 'Concept', 'Thought'],
    'soccer': ['Career', 'Profession', 'Work'],
    'sock': ['Wear', 'Outfit', 'Fashion'],
    'soda': ['Snack', 'Meal', 'Tasty'],
    'sofa': ['Household', 'Home', 'Indoor'],
    'soil': ['Outdoors', 'Natural', 'Earth'],
    'soldier': ['Career', 'Profession', 'Work'],
    'song': ['Music', 'Tune', 'Guitar'],
    'soothe': ['Place', 'Spot', 'Area'],
    'sort': ['Action', 'Doing', 'Verb'],
    'sound': ['Place', 'Spot', 'Area'],
    'soup': ['Snack', 'Meal', 'Tasty'],
    'sow': ['Thing', 'Item', 'Object'],
    'spark': ['Thing', 'Item', 'Object'],
    'sparkle': ['Person', 'Someone', 'People'],
    'speak': ['Talk', 'Voice', 'Discuss'],
    'speaker': ['Career', 'Profession', 'Work'],
    'spear': ['Person', 'Someone', 'People'],
    'speed': ['Person', 'Someone', 'People'],
    'spend': ['Place', 'Spot', 'Area'],
    'spider': ['Creature', 'Critter', 'Wildlife'],
    'spill': ['Place', 'Spot', 'Area'],
    'spin': ['Move', 'Go', 'Travel'],
    'spinach': ['Idea', 'Concept', 'Thought'],
    'splash': ['Water', 'Wet', 'Liquid'],
    'split': ['Action', 'Doing', 'Verb'],
    'sponge': ['Idea', 'Concept', 'Thought'],
    'spoon': ['Tool', 'Utensil', 'Gear'],
    'spring': ['Tool', 'Utensil', 'Gear'],
    'square': ['Location', 'Building', 'Spot'],
    'squeeze': ['Thing', 'Item', 'Object'],
    'stable': ['Quality', 'Trait', 'Describe'],
    'stadium': ['Location', 'Building', 'Spot'],
    'stair': ['Idea', 'Concept', 'Thought'],
    'stamp': ['Household', 'Home', 'Indoor'],
    'stand': ['Place', 'Spot', 'Area'],
    'star': ['Outdoors', 'Natural', 'Earth'],
    'stare': ['Place', 'Spot', 'Area'],
    'start': ['Place', 'Spot', 'Area'],
    'state': ['Action', 'Doing', 'Change'],
    'statue': ['Idea', 'Concept', 'Thought'],
    'steel': ['Action', 'Doing', 'Verb'],
    'steer': ['Career', 'Profession', 'Work'],
    'stethoscope': ['Action', 'Doing', 'Verb'],
    'stir': ['Make', 'Create', 'Build'],
    'stomach': ['Anatomy', 'Human', 'Flesh'],
    'stone': ['Outdoors', 'Natural', 'Earth'],
    'stop': ['Person', 'Someone', 'People'],
    'store': ['Location', 'Building', 'Spot'],
    'storm': ['Outdoors', 'Natural', 'Earth'],
    'story': ['Idea', 'Concept', 'Thought'],
    'stove': ['Household', 'Home', 'Indoor'],
    'straighten': ['Action', 'Doing', 'Verb'],
    'stranger': ['Career', 'Profession', 'Work'],
    'strawberry': ['Snack', 'Meal', 'Tasty'],
    'street': ['Location', 'Building', 'Spot'],
    'strength': ['Person', 'Someone', 'People'],
    'stress': ['Emotion', 'Feeling', 'Mood'],
    'string': ['Place', 'Spot', 'Area'],
    'student': ['Career', 'Profession', 'Work'],
    'study': ['Think', 'Mind', 'Idea'],
    'subtract': ['Idea', 'Concept', 'Thought'],
    'subway': ['Transport', 'Travel', 'Ride'],
    'sugar': ['Snack', 'Meal', 'Tasty'],
    'suggest': ['Thing', 'Item', 'Object'],
    'suit': ['Place', 'Spot', 'Area'],
    'suitcase': ['Household', 'Home', 'Indoor'],
    'summer': ['Moment', 'Calendar', 'Season'],
    'sun': ['Outdoors', 'Natural', 'Earth'],
    'support': ['Idea', 'Concept', 'Thought'],
    'suppose': ['Place', 'Spot', 'Area'],
    'surfing': ['Action', 'Doing', 'Verb'],
    'surgeon': ['Action', 'Doing', 'Verb'],
    'surgery': ['Thing', 'Item', 'Object'],
    'swallow': ['Idea', 'Concept', 'Thought'],
    'swan': ['Action', 'Doing', 'Verb'],
    'sweater': ['Career', 'Profession', 'Work'],
    'sweep': ['Place', 'Spot', 'Area'],
    'swim': ['Sport', 'Game', 'Play'],
    'swimming': ['Thing', 'Item', 'Object'],
    'sword': ['Person', 'Someone', 'People'],
    'syringe': ['Person', 'Someone', 'People'],
    'table': ['Household', 'Home', 'Indoor'],
    'tablet': ['Action', 'Doing', 'Verb'],
    'tailor': ['Action', 'Doing', 'Verb'],
    'take': ['Action', 'Doing', 'Verb'],
    'takeoff': ['Action', 'Doing', 'Verb'],
    'talk': ['Speak', 'Voice', 'Discuss'],
    'tank': ['Thing', 'Item', 'Object'],
    'tap': ['Thing', 'Item', 'Object'],
    'taste': ['Thing', 'Item', 'Object'],
    'tax': ['Money', 'Finance', 'Cash'],
    'taxi': ['Transport', 'Travel', 'Ride'],
    'tea': ['Snack', 'Meal', 'Tasty'],
    'teach': ['Idea', 'Concept', 'Thought'],
    'teacher': ['Career', 'Profession', 'Work'],
    'tear': ['Place', 'Spot', 'Area'],
    'tease': ['Thing', 'Item', 'Object'],
    'television': ['Household', 'Home', 'Indoor'],
    'tell': ['Speak', 'Talk', 'Voice'],
    'temperature': ['Place', 'Spot', 'Area'],
    'temple': ['Location', 'Building', 'Spot'],
    'tennis': ['Sport', 'Game', 'Play'],
    'test': ['School', 'Study', 'Learn'],
    'text': ['Place', 'Spot', 'Area'],
    'thank': ['Speak', 'Talk', 'Voice'],
    'theater': ['Location', 'Building', 'Spot'],
    'thermometer': ['Career', 'Profession', 'Work'],
    'think': ['Mind', 'Idea', 'Judge'],
    'thought': ['Action', 'Doing', 'Verb'],
    'thread': ['Idea', 'Concept', 'Thought'],
    'throw': ['Sport', 'Game', 'Play'],
    'thumb': ['Anatomy', 'Human', 'Flesh'],
    'thunder': ['Career', 'Profession', 'Work'],
    'tie': ['Wear', 'Outfit', 'Fashion'],
    'tiger': ['Creature', 'Critter', 'Wildlife'],
    'toaster': ['Career', 'Profession', 'Work'],
    'toe': ['Anatomy', 'Human', 'Flesh'],
    'tomato': ['Snack', 'Meal', 'Tasty'],
    'tongue': ['Anatomy', 'Human', 'Flesh'],
    'tooth': ['Anatomy', 'Human', 'Flesh'],
    'tornado': ['Person', 'Someone', 'People'],
    'touch': ['Idea', 'Concept', 'Thought'],
    'towel': ['Household', 'Home', 'Indoor'],
    'tower': ['Career', 'Profession', 'Work'],
    'town': ['Location', 'Building', 'Spot'],
    'toy': ['Place', 'Spot', 'Area'],
    'tractor': ['Idea', 'Concept', 'Thought'],
    'trade': ['Place', 'Spot', 'Area'],
    'trail': ['Location', 'Building', 'Spot'],
    'train': ['Transport', 'Travel', 'Ride'],
    'trainer': ['Career', 'Profession', 'Work'],
    'transform': ['Place', 'Spot', 'Area'],
    'travel': ['Move', 'Go', 'Attack'],
    'tremble': ['Idea', 'Concept', 'Thought'],
    'trial': ['Quality', 'Trait', 'Describe'],
    'triangle': ['Person', 'Someone', 'People'],
    'trim': ['Person', 'Someone', 'People'],
    'trophy': ['Sport', 'Game', 'Play'],
    'truck': ['Transport', 'Travel', 'Ride'],
    'trumpet': ['Music', 'Tune', 'Song'],
    'trunk': ['Outdoors', 'Natural', 'Earth'],
    'trust': ['Place', 'Spot', 'Area'],
    'tune': ['Music', 'Song', 'Singer'],
    'tunnel': ['Location', 'Building', 'Spot'],
    'turn': ['Move', 'Go', 'Travel'],
    'turtle': ['Creature', 'Critter', 'Wildlife'],
    'tutor': ['Person', 'Someone', 'People'],
    'twin': ['Relative', 'Kin', 'People'],
    'twinkle': ['Action', 'Doing', 'Verb'],
    'twist': ['Move', 'Go', 'Travel'],
    'type': ['Thing', 'Item', 'Object'],
    'umpire': ['Place', 'Spot', 'Area'],
    'uncle': ['Relative', 'Kin', 'People'],
    'understand': ['Think', 'Mind', 'Idea'],
    'unfold': ['Place', 'Spot', 'Area'],
    'uniform': ['Wear', 'Outfit', 'Fashion'],
    'unite': ['Person', 'Someone', 'People'],
    'university': ['School', 'Study', 'Learn'],
    'unlock': ['Idea', 'Concept', 'Thought'],
    'unpack': ['Idea', 'Concept', 'Thought'],
    'unroll': ['Place', 'Spot', 'Area'],
    'unwrap': ['Person', 'Someone', 'People'],
    'upgrade': ['Person', 'Someone', 'People'],
    'vaccine': ['Person', 'Someone', 'People'],
    'valley': ['Location', 'Building', 'Spot'],
    'verdict': ['Place', 'Spot', 'Area'],
    'vet': ['Thing', 'Item', 'Object'],
    'veterinarian': ['Place', 'Spot', 'Area'],
    'vibrate': ['Action', 'Doing', 'Change'],
    'victim': ['Idea', 'Concept', 'Thought'],
    'village': ['Location', 'Building', 'Spot'],
    'violin': ['Music', 'Tune', 'Song'],
    'visit': ['Person', 'Someone', 'People'],
    'visitor': ['Person', 'Someone', 'People'],
    'volcano': ['Outdoors', 'Natural', 'Earth'],
    'volleyball': ['Sport', 'Game', 'Play'],
    'vote': ['Action', 'Doing', 'Verb'],
    'waffle': ['Snack', 'Meal', 'Tasty'],
    'wage': ['Money', 'Finance', 'Cash'],
    'wagon': ['Transport', 'Travel', 'Ride'],
    'wait': ['Idea', 'Concept', 'Thought'],
    'waiter': ['Career', 'Profession', 'Work'],
    'waitress': ['Career', 'Profession', 'Work'],
    'wake': ['Person', 'Someone', 'People'],
    'walk': ['Move', 'Go', 'Travel'],
    'wall': ['Idea', 'Concept', 'Thought'],
    'wallet': ['Wear', 'Outfit', 'Fashion'],
    'want': ['Idea', 'Concept', 'Thought'],
    'war': ['Thing', 'Item', 'Object'],
    'warden': ['Action', 'Doing', 'Verb'],
    'warehouse': ['Location', 'Building', 'Spot'],
    'warn': ['Speak', 'Talk', 'Voice'],
    'wash': ['Thing', 'Item', 'Object'],
    'watch': ['Thing', 'Item', 'Object'],
    'water': ['Snack', 'Meal', 'Tasty'],
    'waterfall': ['Idea', 'Concept', 'Thought'],
    'watermelon': ['Action', 'Doing', 'Verb'],
    'weakness': ['Idea', 'Concept', 'Topic'],
    'weapon': ['Thing', 'Item', 'Object'],
    'weather': ['Career', 'Profession', 'Work'],
    'wedding': ['Place', 'Spot', 'Area'],
    'week': ['Moment', 'Calendar', 'Season'],
    'weigh': ['Idea', 'Concept', 'Thought'],
    'weight': ['Place', 'Spot', 'Area'],
    'welcome': ['Place', 'Spot', 'Area'],
    'whale': ['Creature', 'Critter', 'Wildlife'],
    'wheelchair': ['Idea', 'Concept', 'Thought'],
    'whisper': ['Career', 'Profession', 'Work'],
    'whistle': ['Place', 'Spot', 'Area'],
    'white': ['Shade', 'Paint', 'Hue'],
    'width': ['Person', 'Someone', 'People'],
    'wife': ['Relative', 'Kin', 'People'],
    'win': ['Sport', 'Game', 'Play'],
    'wind': ['Outdoors', 'Natural', 'Earth'],
    'window': ['Household', 'Home', 'Indoor'],
    'wine': ['Snack', 'Meal', 'Tasty'],
    'wink': ['Action', 'Doing', 'Verb'],
    'winter': ['Moment', 'Calendar', 'Season'],
    'wipe': ['Idea', 'Concept', 'Thought'],
    'wish': ['Place', 'Spot', 'Area'],
    'witch': ['Place', 'Spot', 'Area'],
    'witness': ['Idea', 'Concept', 'Topic'],
    'wizard': ['Idea', 'Concept', 'Thought'],
    'wobble': ['Thing', 'Item', 'Object'],
    'wolf': ['Creature', 'Critter', 'Wildlife'],
    'woman': ['Action', 'Doing', 'Verb'],
    'wonder': ['Career', 'Profession', 'Work'],
    'word': ['Person', 'Someone', 'People'],
    'work': ['Action', 'Doing', 'Verb'],
    'workshop': ['Place', 'Spot', 'Area'],
    'worm': ['Place', 'Spot', 'Area'],
    'worry': ['Emotion', 'Feeling', 'Mood'],
    'wrap': ['Idea', 'Concept', 'Thought'],
    'wrench': ['Tool', 'Utensil', 'Gear'],
    'wrestling': ['Action', 'Doing', 'Verb'],
    'wrist': ['Anatomy', 'Human', 'Flesh'],
    'write': ['Make', 'Create', 'Build'],
    'writer': ['Career', 'Profession', 'Work'],
    'yard': ['Location', 'Building', 'Spot'],
    'year': ['Moment', 'Calendar', 'Season'],
    'yell': ['Speak', 'Talk', 'Voice'],
    'yellow': ['Shade', 'Paint', 'Hue'],
    'zebra': ['Stripes', 'Horse', 'Safari'],
    'zipper': ['Career', 'Profession', 'Work'],
  };

  /// Two or three gentle one-word clues per bank word so a studio clue-giver
  /// sounds varied across games. Never the word itself.
  static const Map<String, List<String>> _hints = {
    'kitchen': ['Cooking', 'Stove', 'Recipes'],
    'garden': ['Flowers', 'Soil', 'Backyard'],
    'window': ['Glass', 'View', 'Curtains'],
    'blanket': ['Cozy', 'Warm', 'Bed'],
    'teapot': ['Tea', 'Pour', 'Spout'],
    'pillow': ['Sleep', 'Soft', 'Head'],
    'candle': ['Flame', 'Wax', 'Glow'],
    'mirror': ['Reflection', 'Glass', 'Look'],
    'apple': ['Fruit', 'Orchard', 'Crunchy'],
    'butter': ['Toast', 'Spread', 'Yellow'],
    'cookie': ['Sweet', 'Bake', 'Jar'],
    'coffee': ['Morning', 'Mug', 'Beans'],
    'honey': ['Bee', 'Sweet', 'Golden'],
    'lemon': ['Sour', 'Yellow', 'Zest'],
    'pancake': ['Breakfast', 'Syrup', 'Flat'],
    'popcorn': ['Movie', 'Buttery', 'Kernel'],
    'sunshine': ['Bright', 'Warm', 'Sky'],
    'rainbow': ['Colors', 'Rain', 'Arc'],
    'mountain': ['Tall', 'Climb', 'Peak'],
    'river': ['Water', 'Flow', 'Bank'],
    'flower': ['Petals', 'Bloom', 'Vase'],
    'meadow': ['Grass', 'Field', 'Open'],
    'snowman': ['Winter', 'Frosty', 'Carrot'],
    'breeze': ['Wind', 'Gentle', 'Cool'],
    'puppy': ['Dog', 'Playful', 'Paws'],
    'kitten': ['Cat', 'Purr', 'Tiny'],
    'rabbit': ['Hop', 'Ears', 'Carrot'],
    'robin': ['Bird', 'Spring', 'Feathers'],
    'butterfly': ['Wings', 'Flutter', 'Cocoon'],
    'squirrel': ['Nuts', 'Bushy', 'Tree'],
    'penguin': ['Antarctica', 'Waddle', 'Tuxedo'],
    'turtle': ['Slow', 'Shell', 'Pond'],
    'grandma': ['Family', 'Cookies', 'Hugs'],
    'postcard': ['Mail', 'Vacation', 'Stamp'],
    'bicycle': ['Wheels', 'Pedals', 'Ride'],
    'picnic': ['Park', 'Basket', 'Blanket'],
    'quilt': ['Stitches', 'Patches', 'Cozy'],
    'puzzle': ['Pieces', 'Solve', 'Jigsaw'],
    'melody': ['Song', 'Tune', 'Hum'],
    'birthday': ['Cake', 'Candles', 'Party'],
    'clock': ['Time', 'Tick', 'Hands'],
    'kettle': ['Boil', 'Whistle', 'Tea'],
    'slipper': ['Feet', 'Cozy', 'Soft'],
    'umbrella': ['Rain', 'Open', 'Shade'],
    'pumpkin': ['Orange', 'Autumn', 'Pie'],
    'sandwich': ['Lunch', 'Bread', 'Filling'],
    'seashell': ['Beach', 'Ocean', 'Sand'],
    'thunder': ['Storm', 'Loud', 'Boom'],
    'ladybug': ['Spots', 'Red', 'Tiny'],
    'dolphin': ['Ocean', 'Swim', 'Leap'],
    'holiday': ['Vacation', 'Rest', 'Travel'],
  };
}
