-- ============================================================================
-- Match Word — COMPLETE database schema (all migrations 0001 → 0012)
--
-- Paste this ENTIRE file into the Supabase SQL Editor and click Run ONCE.
-- It is idempotent-friendly and must be applied in full for the app to work.
-- (Applying only 0001_init.sql makes sign-in work but every game/character
--  action fail with "Something went wrong".)
--
-- Generated by concatenating supabase/migrations/*.sql in order.
-- ============================================================================


-- ============================================================================
-- 0001_init.sql
-- ============================================================================
-- Match Word — Milestone 1 schema
-- Sign In & Account System: profiles + device-id trial-abuse ledger.
-- Run this in the Supabase SQL editor (or via the CLI migrations).

-- =============================================================================
-- profiles
-- =============================================================================
create table if not exists public.profiles (
  id                uuid primary key references auth.users (id) on delete cascade,
  first_name        text not null,
  device_id         text not null,
  pin_hash          text not null,
  pin_salt          text not null,
  trial_used        boolean not null default false,
  trial_started_at  timestamptz,
  created_at        timestamptz not null default now()
);

comment on table public.profiles is
  'Player profile. Email lives in auth.users (recovery only) and is never shown.';

-- =============================================================================
-- device_trials  (silent free-trial abuse prevention — device id is primary)
-- =============================================================================
create table if not exists public.device_trials (
  device_id      text primary key,
  first_trial_at timestamptz not null default now(),
  ip_address     text  -- reserved for the later-phase IP layer
);

comment on table public.device_trials is
  'One row per device that has ever started a free trial.';

-- =============================================================================
-- Row Level Security
-- =============================================================================
alter table public.profiles enable row level security;
alter table public.device_trials enable row level security;

-- profiles: a user may only see and change their own row.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- device_trials: any authenticated user may check/record a device id.
-- (No row is tied to a user; this is an anonymous ledger.)
drop policy if exists "device_trials_select" on public.device_trials;
create policy "device_trials_select"
  on public.device_trials for select
  to authenticated
  using (true);

drop policy if exists "device_trials_insert" on public.device_trials;
create policy "device_trials_insert"
  on public.device_trials for insert
  to authenticated
  with check (true);


-- ============================================================================
-- 0002_characters.sql
-- ============================================================================
-- Match Word — Milestone 3 schema
-- Character Creation System: store each player's assembled character.
-- Run this in the Supabase SQL editor after 0001_init.sql.

-- =============================================================================
-- characters  (one paper-doll character per profile)
-- =============================================================================
create table if not exists public.characters (
  profile_id    uuid primary key references public.profiles (id) on delete cascade,
  display_name  text not null,
  base          text,   -- layer option ids (null/None handled gracefully)
  base_color    text,   -- skin-tone tint applied to the chosen body
  hair          text,
  hair_color    text,   -- tint id applied to the neutral hair PNG
  eyes          text,
  eye_color     text,   -- tint id applied to the neutral eyes PNG
  glasses       text,
  outfit        text,
  updated_at    timestamptz not null default now()
);

-- Backfill for projects created before the colour columns existed.
alter table public.characters add column if not exists base_color text;
alter table public.characters add column if not exists hair_color text;
alter table public.characters add column if not exists eye_color  text;

comment on table public.characters is
  'A player''s assembled paper-doll character. Layer columns store option ids; '
  'null means the player chose None for that layer.';

-- =============================================================================
-- Row Level Security — a user may only see and change their own character.
-- =============================================================================
alter table public.characters enable row level security;

drop policy if exists "characters_select_own" on public.characters;
create policy "characters_select_own"
  on public.characters for select
  using (auth.uid() = profile_id);

drop policy if exists "characters_insert_own" on public.characters;
create policy "characters_insert_own"
  on public.characters for insert
  with check (auth.uid() = profile_id);

drop policy if exists "characters_update_own" on public.characters;
create policy "characters_update_own"
  on public.characters for update
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);


-- ============================================================================
-- 0003_pin_verify.sql
-- ============================================================================
-- Match Word — Milestone 1 hardening
-- Cross-device sign-in: verify a 4-digit PIN on the server BEFORE a session
-- exists, so the app can show email -> PIN -> one-time-code in that order on a
-- fresh device.
--
-- Security model:
--  * The PIN hash is never sent to the client; verification happens in the DB.
--  * Verifying the PIN does NOT grant a session — the emailed one-time code is
--    still the gate that establishes the session. This is defence in depth: a
--    guessed PIN alone cannot sign anyone in.
--  * Attempts are rate-limited (lockout after repeated failures) because a
--    4-digit PIN is low entropy.
--
-- Run this in the Supabase SQL editor after 0002_characters.sql.

create extension if not exists pgcrypto with schema extensions;

-- =============================================================================
-- mw_hash_pin — reproduces the app's PinHasher exactly.
--   PinHasher: bytes = utf8("salt:pin"); repeat 50000x: bytes = sha256(bytes);
--   result = base64url(bytes)  (URL-safe alphabet, '=' padding kept).
-- =============================================================================
create or replace function public.mw_hash_pin(p_salt text, p_pin text)
returns text
language plpgsql
immutable
set search_path = public, extensions
as $$
declare
  b bytea;
  i int;
begin
  b := convert_to(p_salt || ':' || p_pin, 'UTF8');
  for i in 1..50000 loop
    b := extensions.digest(b, 'sha256');
  end loop;
  -- Postgres base64 -> URL-safe base64 (strip any line breaks, swap +/ for -_).
  return translate(replace(encode(b, 'base64'), E'\n', ''), '+/', '-_');
end;
$$;

-- =============================================================================
-- pin_attempts — per-account brute-force throttle for pre-session PIN checks.
-- No RLS policies: only the SECURITY DEFINER function (running as owner) writes
-- it; the anon/authenticated API roles cannot read or change it directly.
-- =============================================================================
create table if not exists public.pin_attempts (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  fail_count   int not null default 0,
  locked_until timestamptz,
  updated_at   timestamptz not null default now()
);

alter table public.pin_attempts enable row level security;
revoke all on table public.pin_attempts from anon, authenticated;

-- =============================================================================
-- mw_verify_pin — look up an account by email and check its PIN, rate-limited.
-- Returns JSON: {ok:true, name:text} on success, otherwise
--   {ok:false, reason:'no_account'|'bad_pin'|'locked', retry_seconds:int}.
-- Verifying the PIN does not create a session; the caller must still complete
-- the emailed one-time-code step to sign in.
-- =============================================================================
create or replace function public.mw_verify_pin(p_email text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_uid          uuid;
  v_name         text;
  v_hash         text;
  v_salt         text;
  v_fail         int := 0;
  v_locked_until timestamptz;
  v_threshold    constant int := 5;         -- failures before a lockout
  v_lock_window  constant interval := interval '15 minutes';
begin
  -- Resolve the account by email (case-insensitive).
  select u.id into v_uid
    from auth.users u
   where lower(u.email) = lower(trim(p_email))
   limit 1;

  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'no_account');
  end if;

  select p.first_name, p.pin_hash, p.pin_salt
    into v_name, v_hash, v_salt
    from public.profiles p
   where p.id = v_uid;

  if v_hash is null or v_salt is null then
    return jsonb_build_object('ok', false, 'reason', 'no_account');
  end if;

  -- Enforce any active lockout.
  select fail_count, locked_until
    into v_fail, v_locked_until
    from public.pin_attempts
   where user_id = v_uid;

  if v_locked_until is not null and v_locked_until > now() then
    return jsonb_build_object(
      'ok', false,
      'reason', 'locked',
      'retry_seconds', ceil(extract(epoch from (v_locked_until - now())))::int
    );
  end if;

  -- Check the PIN.
  if public.mw_hash_pin(v_salt, p_pin) = v_hash then
    -- Success: clear any failure state.
    insert into public.pin_attempts (user_id, fail_count, locked_until, updated_at)
    values (v_uid, 0, null, now())
    on conflict (user_id)
    do update set fail_count = 0, locked_until = null, updated_at = now();

    return jsonb_build_object('ok', true, 'name', v_name);
  end if;

  -- Failure: increment and possibly lock.
  v_fail := coalesce(v_fail, 0) + 1;
  if v_fail >= v_threshold then
    insert into public.pin_attempts (user_id, fail_count, locked_until, updated_at)
    values (v_uid, 0, now() + v_lock_window, now())
    on conflict (user_id)
    do update set fail_count = 0, locked_until = now() + v_lock_window, updated_at = now();

    return jsonb_build_object(
      'ok', false,
      'reason', 'locked',
      'retry_seconds', ceil(extract(epoch from v_lock_window))::int
    );
  end if;

  insert into public.pin_attempts (user_id, fail_count, locked_until, updated_at)
  values (v_uid, v_fail, null, now())
  on conflict (user_id)
  do update set fail_count = v_fail, locked_until = null, updated_at = now();

  return jsonb_build_object('ok', false, 'reason', 'bad_pin');
end;
$$;

-- Only the two API roles may call it (not arbitrary PUBLIC grantees).
revoke all on function public.mw_verify_pin(text, text) from public;
grant execute on function public.mw_verify_pin(text, text) to anon, authenticated;

-- mw_hash_pin is a helper for mw_verify_pin; do not expose it to the API.
revoke all on function public.mw_hash_pin(text, text) from public;


-- ============================================================================
-- 0004_lobby.sql
-- ============================================================================
-- Match Word — Milestone 4 schema
-- Lobby, Game Codes & Matchmaking.
-- Run this in the Supabase SQL editor after 0003_pin_verify.sql.
--
-- Design notes
-- ------------
-- * A game is a room of up to 4 seats split into two teams (A and B).
--   Seat -> team/role mapping (kept in sync with the Dart LobbyRoles helper):
--       seat 0 -> Team A, role A1 (host)
--       seat 1 -> Team B, role B1
--       seat 2 -> Team A, role A2
--       seat 3 -> Team B, role B2
-- * All writes are server-authoritative: every mutation goes through a
--   SECURITY DEFINER function below. The tables have RLS enabled with SELECT
--   policies only, so clients can read the lobby they belong to (and public
--   games) but can never insert/update/delete rows directly.
-- * "Computer" seat-fill uses game_players.is_ai. The player-facing UI never
--   surfaces that wording — these simply appear as extra studio players.

-- =============================================================================
-- games  (one row per lobby / room)
-- =============================================================================
create table if not exists public.games (
  id           uuid primary key default gen_random_uuid(),
  code         text not null,
  host_id      uuid not null references public.profiles (id) on delete cascade,
  status       text not null default 'lobby'
                 check (status in ('lobby', 'in_progress', 'finished', 'cancelled')),
  is_public    boolean not null default false,
  max_players  int not null default 4 check (max_players between 2 and 4),
  created_at   timestamptz not null default now(),
  started_at   timestamptz,
  expires_at   timestamptz not null default now() + interval '24 hours',
  updated_at   timestamptz not null default now()
);

comment on table public.games is
  'A Match Word lobby/room. Codes are unique among active (lobby) games and '
  'expire after 24h.';

-- Only one active game may hold a given code at a time.
create unique index if not exists games_active_code_idx
  on public.games (code)
  where status = 'lobby';

create index if not exists games_public_lobby_idx
  on public.games (is_public, status, created_at);

-- =============================================================================
-- game_players  (seats within a game; a null profile_id is a computer seat)
-- =============================================================================
create table if not exists public.game_players (
  id           uuid primary key default gen_random_uuid(),
  game_id      uuid not null references public.games (id) on delete cascade,
  profile_id   uuid references public.profiles (id) on delete cascade,
  display_name text not null,
  first_name   text not null,
  is_ai        boolean not null default false,
  is_host      boolean not null default false,
  seat         int not null check (seat between 0 and 3),
  team         text not null check (team in ('A', 'B')),
  role         text not null check (role in ('A1', 'A2', 'B1', 'B2')),
  joined_at    timestamptz not null default now(),
  unique (game_id, seat)
);

-- A human may hold at most one seat per game.
create unique index if not exists game_players_unique_human_idx
  on public.game_players (game_id, profile_id)
  where profile_id is not null;

create index if not exists game_players_game_idx
  on public.game_players (game_id);

comment on table public.game_players is
  'Seats within a game. profile_id null = computer-filled seat (is_ai).';

-- =============================================================================
-- Helper: map a seat number to its (team, role).
-- =============================================================================
create or replace function public.mw_seat_team(p_seat int)
returns text language sql immutable as $$
  select case when p_seat % 2 = 0 then 'A' else 'B' end;
$$;

create or replace function public.mw_seat_role(p_seat int)
returns text language sql immutable as $$
  select public.mw_seat_team(p_seat) || ((p_seat / 2) + 1)::text;
$$;

-- =============================================================================
-- Helper: generate a 4-digit code not currently used by an active lobby.
-- =============================================================================
create or replace function public.mw_new_game_code()
returns text language plpgsql as $$
declare
  v_code text;
  v_tries int := 0;
begin
  loop
    v_code := lpad((floor(random() * 10000))::int::text, 4, '0');
    exit when not exists (
      select 1 from public.games
      where code = v_code and status = 'lobby'
    );
    v_tries := v_tries + 1;
    if v_tries > 50 then
      raise exception 'could_not_allocate_code';
    end if;
  end loop;
  return v_code;
end;
$$;

-- =============================================================================
-- Create a game. The caller becomes the host in seat 0 (Team A / A1).
-- Returns: { ok, game_id, code }
-- =============================================================================
create or replace function public.mw_create_game(p_is_public boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_name  text;
  v_code  text;
  v_game  uuid;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select first_name into v_name from public.profiles where id = v_uid;
  if v_name is null then
    return jsonb_build_object('ok', false, 'reason', 'no_profile');
  end if;

  v_code := public.mw_new_game_code();

  insert into public.games (code, host_id, is_public)
  values (v_code, v_uid, coalesce(p_is_public, false))
  returning id into v_game;

  insert into public.game_players
    (game_id, profile_id, display_name, first_name, is_host, seat, team, role)
  values
    (v_game, v_uid, v_name, v_name, true, 0,
     public.mw_seat_team(0), public.mw_seat_role(0));

  return jsonb_build_object('ok', true, 'game_id', v_game, 'code', v_code);
end;
$$;

-- =============================================================================
-- Internal: seat the current user into a game. Assumes the game is joinable.
-- Returns the assigned seat, or -1 if the game is full.
-- =============================================================================
create or replace function public.mw_seat_current_user(p_game uuid)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_name  text;
  v_max   int;
  v_seat  int;
begin
  -- Already seated? Return the existing seat (idempotent join).
  select seat into v_seat
  from public.game_players
  where game_id = p_game and profile_id = v_uid;
  if v_seat is not null then
    return v_seat;
  end if;

  select max_players into v_max from public.games where id = p_game;
  select first_name into v_name from public.profiles where id = v_uid;

  -- Lowest free seat in [0, max_players).
  select s.seat into v_seat
  from generate_series(0, v_max - 1) as s(seat)
  where not exists (
    select 1 from public.game_players gp
    where gp.game_id = p_game and gp.seat = s.seat
  )
  order by s.seat
  limit 1;

  if v_seat is null then
    return -1;
  end if;

  insert into public.game_players
    (game_id, profile_id, display_name, first_name, is_host, seat, team, role)
  values
    (p_game, v_uid, v_name, v_name, false, v_seat,
     public.mw_seat_team(v_seat), public.mw_seat_role(v_seat));

  return v_seat;
end;
$$;

-- =============================================================================
-- Join a game by its 4-digit code.
-- Returns: { ok, game_id } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_join_game(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_game  uuid;
  v_seat  int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select id into v_game
  from public.games
  where code = p_code and status = 'lobby' and expires_at > now()
  order by created_at desc
  limit 1;

  if v_game is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  v_seat := public.mw_seat_current_user(v_game);
  if v_seat < 0 then
    return jsonb_build_object('ok', false, 'reason', 'full');
  end if;

  return jsonb_build_object('ok', true, 'game_id', v_game);
end;
$$;

-- =============================================================================
-- Quick match: join the oldest open public lobby with a free seat, or create a
-- new public game if none is available.
-- Returns: { ok, game_id, matched }
-- =============================================================================
create or replace function public.mw_quick_match()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_game  uuid;
  v_seat  int;
  v_res   jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select g.id into v_game
  from public.games g
  where g.is_public
    and g.status = 'lobby'
    and g.expires_at > now()
    and not exists (
      select 1 from public.game_players gp
      where gp.game_id = g.id and gp.profile_id = v_uid
    )
    and (
      select count(*) from public.game_players gp where gp.game_id = g.id
    ) < g.max_players
  order by g.created_at asc
  limit 1;

  if v_game is null then
    v_res := public.mw_create_game(true);
    return v_res || jsonb_build_object('matched', false);
  end if;

  v_seat := public.mw_seat_current_user(v_game);
  if v_seat < 0 then
    -- Raced and lost the last seat; fall back to a fresh public game.
    v_res := public.mw_create_game(true);
    return v_res || jsonb_build_object('matched', false);
  end if;

  return jsonb_build_object('ok', true, 'game_id', v_game, 'matched', true);
end;
$$;

-- =============================================================================
-- Host action: fill the remaining empty seats with computer players.
-- Returns: { ok, added } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_fill_seats(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid       uuid := auth.uid();
  v_host      uuid;
  v_max       int;
  v_status    text;
  v_seat      int;
  v_added     int := 0;
  v_pool      text[] := array[
    'Sunny', 'Rosie', 'Buddy', 'Pearl', 'Gus', 'Mabel', 'Otis', 'Ada',
    'Walter', 'Rosa', 'Frank', 'Helen', 'Betty', 'Joe', 'Doris', 'Sam',
    'Nancy', 'Bill', 'Grace', 'Tom', 'Linda', 'Arthur', 'Margaret', 'Max'
  ];
  v_taken     text[] := array[]::text[];
  v_shuffled  text[];
  v_name      text;
  v_i         int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select host_id, max_players, status
    into v_host, v_max, v_status
  from public.games where id = p_game;

  if v_host is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if v_host <> v_uid then
    return jsonb_build_object('ok', false, 'reason', 'not_host');
  end if;
  if v_status <> 'lobby' then
    return jsonb_build_object('ok', false, 'reason', 'not_in_lobby');
  end if;

  select coalesce(array_agg(lower(display_name)), array[]::text[])
    into v_taken
  from public.game_players
  where game_id = p_game;

  select array_agg(n order by md5(p_game::text || ':' || n))
    into v_shuffled
  from unnest(v_pool) as n;

  v_i := 1;
  for v_seat in 0 .. v_max - 1 loop
    if not exists (
      select 1 from public.game_players gp
      where gp.game_id = p_game and gp.seat = v_seat
    ) then
      v_name := null;
      while v_i <= coalesce(array_length(v_shuffled, 1), 0) loop
        if not (lower(v_shuffled[v_i]) = any (v_taken)) then
          v_name := v_shuffled[v_i];
          v_i := v_i + 1;
          exit;
        end if;
        v_i := v_i + 1;
      end loop;
      if v_name is null then
        v_name := 'Player' || (v_seat + 1)::text;
      end if;

      insert into public.game_players
        (game_id, profile_id, display_name, first_name, is_ai, seat, team, role)
      values
        (p_game, null, v_name, v_name, true, v_seat,
         public.mw_seat_team(v_seat), public.mw_seat_role(v_seat));
      v_taken := array_append(v_taken, lower(v_name));
      v_added := v_added + 1;
    end if;
  end loop;

  update public.games set updated_at = now() where id = p_game;
  return jsonb_build_object('ok', true, 'added', v_added);
end;
$$;

-- =============================================================================
-- Leave a game. If the host leaves, hand off to the next human, or cancel the
-- game when no humans remain.
-- Returns: { ok }
-- =============================================================================
create or replace function public.mw_leave_game(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid      uuid := auth.uid();
  v_was_host boolean;
  v_new_host uuid;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select is_host into v_was_host
  from public.game_players
  where game_id = p_game and profile_id = v_uid;

  delete from public.game_players
  where game_id = p_game and profile_id = v_uid;

  if coalesce(v_was_host, false) then
    -- Promote the lowest-seat remaining human, if any.
    select profile_id into v_new_host
    from public.game_players
    where game_id = p_game and profile_id is not null
    order by seat asc
    limit 1;

    if v_new_host is null then
      update public.games
        set status = 'cancelled', updated_at = now()
      where id = p_game;
    else
      update public.game_players set is_host = false where game_id = p_game;
      update public.game_players set is_host = true
        where game_id = p_game and profile_id = v_new_host;
      update public.games
        set host_id = v_new_host, updated_at = now()
      where id = p_game;
    end if;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

-- =============================================================================
-- Host action: start the game (lobby -> in_progress).
-- Returns: { ok } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_start_game(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid    uuid := auth.uid();
  v_host   uuid;
  v_status text;
  v_count  int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select host_id, status into v_host, v_status
  from public.games where id = p_game;

  if v_host is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if v_host <> v_uid then
    return jsonb_build_object('ok', false, 'reason', 'not_host');
  end if;
  if v_status <> 'lobby' then
    return jsonb_build_object('ok', false, 'reason', 'not_in_lobby');
  end if;

  select count(*) into v_count from public.game_players where game_id = p_game;
  if v_count < 2 then
    return jsonb_build_object('ok', false, 'reason', 'need_more_players');
  end if;

  update public.games
    set status = 'in_progress', started_at = now(), updated_at = now()
  where id = p_game;

  return jsonb_build_object('ok', true);
end;
$$;

-- =============================================================================
-- Row Level Security
--   Reads: members can see their game + its players; anyone signed in can see
--   open public lobbies. Writes: none direct — the SECURITY DEFINER functions
--   above are the only way to mutate lobby state (server-authoritative).
-- =============================================================================
alter table public.games        enable row level security;
alter table public.game_players enable row level security;

drop policy if exists "games_select_visible" on public.games;
create policy "games_select_visible"
  on public.games for select
  using (
    (is_public and status = 'lobby')
    or exists (
      select 1 from public.game_players gp
      where gp.game_id = id and gp.profile_id = auth.uid()
    )
  );

drop policy if exists "game_players_select_visible" on public.game_players;
create policy "game_players_select_visible"
  on public.game_players for select
  using (
    exists (
      select 1 from public.game_players me
      where me.game_id = game_players.game_id and me.profile_id = auth.uid()
    )
    or exists (
      select 1 from public.games g
      where g.id = game_players.game_id and g.is_public and g.status = 'lobby'
    )
  );

-- =============================================================================
-- Realtime: broadcast lobby changes to subscribed clients.
-- =============================================================================
do $$
begin
  begin
    alter publication supabase_realtime add table public.games;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.game_players;
  exception when duplicate_object then null;
  end;
end $$;


-- ============================================================================
-- 0005_lobby_counts.sql
-- ============================================================================
-- Match Word — Milestone 4 follow-up
-- "Check Upcoming Games" list with player counts.
-- Run this in the Supabase SQL editor after 0004_lobby.sql.
--
-- Why this exists
-- ---------------
-- The spec's definition of done for the lobby hub calls for an upcoming-games
-- list *with player counts* so a senior can see, at a glance, how full each
-- open game is ("2 / 4 players") before joining. Rather than have the client
-- issue one count query per row (N+1) or read the seats table directly, this
-- single SECURITY DEFINER function returns each joinable public lobby together
-- with its live occupancy. Full games are excluded because they cannot be
-- joined anyway.

create or replace function public.mw_list_open_games()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(to_jsonb(t) order by t.created_at desc),
    '[]'::jsonb
  )
  from (
    select
      g.id,
      g.code,
      g.host_id,
      g.status,
      g.is_public,
      g.max_players,
      g.created_at,
      g.started_at,
      g.expires_at,
      (
        select count(*)::int
        from public.game_players gp
        where gp.game_id = g.id
      ) as player_count
    from public.games g
    where g.is_public
      and g.status = 'lobby'
      and g.expires_at > now()
      and (
        select count(*)
        from public.game_players gp
        where gp.game_id = g.id
      ) < g.max_players
    order by g.created_at desc
    limit 20
  ) t;
$$;

comment on function public.mw_list_open_games() is
  'Joinable public lobbies (not full, not expired) with live player_count, '
  'for the "Check Upcoming Games" list.';

grant execute on function public.mw_list_open_games() to authenticated;


-- ============================================================================
-- 0006_lobby_rls_fix.sql
-- ============================================================================
-- Match Word — Milestone 4 hotfix
-- Fix: infinite recursion in the game_players / games SELECT policies.
-- Run this in the Supabase SQL editor after 0005_lobby_counts.sql.
--
-- Why this is needed
-- ------------------
-- The original `game_players_select_visible` policy (0004) queried
-- public.game_players from *inside* its own SELECT USING clause. Postgres
-- re-applies the same policy to that inner query, which recurses forever and
-- raises `42P17: infinite recursion detected in policy for relation
-- "game_players"`. The `games_select_visible` policy inherited the same failure
-- through its game_players sub-query.
--
-- Effect in the app: mw_create_game / mw_join_game / mw_quick_match all succeed
-- (they are SECURITY DEFINER and bypass RLS), so the room is created on the
-- server, but the very next client read — loadPlayers() / watchPlayers(), a
-- plain select on game_players — hits the recursive policy and throws, so the
-- lobby surfaces "Something went wrong. Please try again." even though the game
-- exists. The open-games list keeps working because it goes through the
-- SECURITY DEFINER mw_list_open_games() function instead of a direct select.
--
-- The fix: check membership through a SECURITY DEFINER helper. Because the
-- helper runs as its owner, RLS is not applied inside it, so the self-reference
-- no longer recurses.

-- =============================================================================
-- Helper: is the current user seated in this game? (RLS-safe membership check)
-- =============================================================================
create or replace function public.mw_is_game_member(p_game uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.game_players gp
    where gp.game_id = p_game
      and gp.profile_id = auth.uid()
  );
$$;

comment on function public.mw_is_game_member(uuid) is
  'RLS-safe membership check used by the games/game_players SELECT policies to '
  'avoid infinite recursion (runs SECURITY DEFINER so RLS is not re-applied).';

grant execute on function public.mw_is_game_member(uuid) to authenticated;

-- =============================================================================
-- Re-create the SELECT policies without any self-referential sub-query.
-- =============================================================================

-- games: members can read their game; anyone signed in can read open public
-- lobbies.
drop policy if exists "games_select_visible" on public.games;
create policy "games_select_visible"
  on public.games for select
  using (
    (is_public and status = 'lobby')
    or public.mw_is_game_member(id)
  );

-- game_players: members can read every seat in a game they belong to; anyone
-- signed in can read the seats of open public lobbies.
drop policy if exists "game_players_select_visible" on public.game_players;
create policy "game_players_select_visible"
  on public.game_players for select
  using (
    public.mw_is_game_member(game_id)
    or exists (
      select 1
      from public.games g
      where g.id = game_players.game_id
        and g.is_public
        and g.status = 'lobby'
    )
  );


-- ============================================================================
-- 0007_gameplay.sql
-- ============================================================================
-- Match Word — Milestone 5 schema
-- Core Gameplay Engine: server-authoritative turns, steals, auto-reveal,
-- scoring, and the first-half / halftime / second-half role switch.
-- Run this in the Supabase SQL editor after 0006_lobby_rls_fix.sql.
--
-- Design notes
-- ------------
-- * The authoritative rules live here and are mirrored 1:1 by the pure-Dart
--   engine in app/lib/features/game/game_engine.dart (and its tests), so the
--   client can render optimistically while the server stays the source of
--   truth. Keep the two in lock-step when either changes.
-- * A game (from 0004_lobby.sql) that is 'in_progress' gets exactly one
--   game_state row plus a dealt list of game_words. Every clue and guess is
--   appended to game_plays (the shared real-time feed).
-- * All writes are server-authoritative: clients only ever read these tables
--   (RLS SELECT policies via mw_is_game_member); the SECURITY DEFINER functions
--   below are the only write path.
-- * Roles: Team A = seats 0/2 (A1/A2), Team B = seats 1/3 (B1/B2). In the first
--   half role '1' gives clues and role '2' guesses; at halftime they switch.

-- =============================================================================
-- Membership helper (mirrors 0006_lobby_rls_fix.sql).
-- Defined here with `create or replace` so this migration is self-sufficient
-- and can be applied even if 0006 has not run yet. It is RLS-safe (SECURITY
-- DEFINER, so RLS is not re-applied inside it) and is used by the SELECT
-- policies below. Running it again after 0006 is a harmless no-op.
-- =============================================================================
create or replace function public.mw_is_game_member(p_game uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.game_players gp
    where gp.game_id = p_game
      and gp.profile_id = auth.uid()
  );
$$;

grant execute on function public.mw_is_game_member(uuid) to authenticated;

-- =============================================================================
-- game_state  (one row per in-progress game — the live match snapshot)
-- =============================================================================
create table if not exists public.game_state (
  game_id        uuid primary key references public.games (id) on delete cascade,
  phase          text not null default 'first_half'
                   check (phase in ('first_half', 'halftime', 'second_half', 'game_over')),
  word_index     int  not null default 0,
  cluing_team    text not null default 'A' check (cluing_team in ('A', 'B')),
  step           text not null default 'awaiting_clue'
                   check (step in ('awaiting_clue', 'awaiting_guess', 'resolved')),
  exchange_count int  not null default 0,
  score_a        int  not null default 0,
  score_b        int  not null default 0,
  pending_clue   text,
  last_outcome   text not null default 'none'
                   check (last_outcome in ('none', 'guessed', 'revealed')),
  host_line      text not null default '',
  words_per_half int  not null default 6,
  max_exchanges  int  not null default 5,
  word_value     int  not null default 5,
  updated_at     timestamptz not null default now()
);

comment on table public.game_state is
  'Live, server-authoritative snapshot of an in-progress Match Word game. '
  'Mirrors the Dart MatchState in app/lib/features/game/game_engine.dart.';

-- =============================================================================
-- game_words  (the secret words dealt for a game, in play order)
-- =============================================================================
create table if not exists public.game_words (
  game_id    uuid not null references public.games (id) on delete cascade,
  word_index int  not null,
  word       text not null,
  primary key (game_id, word_index)
);

-- =============================================================================
-- game_plays  (the shared feed: one row per clue or guess)
-- =============================================================================
create table if not exists public.game_plays (
  id          uuid primary key default gen_random_uuid(),
  game_id     uuid not null references public.games (id) on delete cascade,
  word_index  int  not null,
  kind        text not null check (kind in ('clue', 'guess')),
  team        text not null check (team in ('A', 'B')),
  role        text not null check (role in ('A1', 'A2', 'B1', 'B2')),
  player_name text not null,
  text        text not null,
  correct     boolean,
  created_at  timestamptz not null default now()
);

create index if not exists game_plays_game_idx
  on public.game_plays (game_id, created_at);

-- =============================================================================
-- Rules helpers (kept identical to the Dart MatchEngine).
-- =============================================================================

-- The team that opens a given word — teams alternate who starts.
create or replace function public.mw_starting_team(p_word_index int)
returns text language sql immutable as $$
  select case when p_word_index % 2 = 0 then 'A' else 'B' end;
$$;

-- Clue-giver role for a team in a phase (role switch at halftime).
create or replace function public.mw_clue_giver_role(p_team text, p_phase text)
returns text language sql immutable as $$
  select p_team || case when p_phase = 'second_half' then '2' else '1' end;
$$;

-- Guesser role for a team in a phase.
create or replace function public.mw_guesser_role(p_team text, p_phase text)
returns text language sql immutable as $$
  select p_team || case when p_phase = 'second_half' then '1' else '2' end;
$$;

-- Case/whitespace-insensitive word comparison.
create or replace function public.mw_word_matches(p_guess text, p_word text)
returns boolean language sql immutable as $$
  select length(btrim(lower(p_word))) > 0
     and regexp_replace(btrim(lower(p_guess)), '\s+', ' ', 'g')
       = regexp_replace(btrim(lower(p_word)),  '\s+', ' ', 'g');
$$;

-- Current point value of the word given exchanges spent (floor 1).
create or replace function public.mw_word_value(p_base int, p_exchanges int)
returns int language sql immutable as $$
  select greatest(1, p_base - p_exchanges);
$$;

-- The host's "give a clue" prompt for a team/phase.
create or replace function public.mw_clue_prompt(p_game uuid, p_team text, p_phase text)
returns text language plpgsql stable as $$
declare
  v_role text := public.mw_clue_giver_role(p_team, p_phase);
  v_name text;
begin
  select display_name into v_name
  from public.game_players
  where game_id = p_game and role = v_role;
  v_name := coalesce(v_name, 'Player ' || v_role);
  return v_name || ', give a one-word clue.';
end;
$$;

-- =============================================================================
-- Begin play: deal words and create the game_state for an in-progress game.
-- Idempotent — a second call is a no-op once state exists. Host only.
-- Returns: { ok } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_begin_play(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid    uuid := auth.uid();
  v_host   uuid;
  v_status text;
  v_wph    int  := 6;   -- words per half (Ronna: 6 rounds/side)
  v_total  int;
  v_team   text;
  i        int;
  v_word   text;
  v_bank   text[] := array[
    'Kitchen','Garden','Window','Blanket','Teapot','Pillow','Candle','Mirror',
    'Apple','Butter','Cookie','Coffee','Honey','Lemon','Pancake','Popcorn',
    'Sunshine','Rainbow','Mountain','River','Flower','Meadow','Snowman','Breeze',
    'Puppy','Kitten','Rabbit','Robin','Butterfly','Squirrel','Penguin','Turtle',
    'Grandma','Postcard','Bicycle','Picnic','Quilt','Puzzle','Melody','Birthday'
  ];
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select host_id, status into v_host, v_status
  from public.games where id = p_game;

  if v_host is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if v_host <> v_uid then
    return jsonb_build_object('ok', false, 'reason', 'not_host');
  end if;
  if v_status <> 'in_progress' then
    return jsonb_build_object('ok', false, 'reason', 'not_started');
  end if;

  -- Already dealt? Idempotent success.
  if exists (select 1 from public.game_state where game_id = p_game) then
    return jsonb_build_object('ok', true, 'already', true);
  end if;

  v_total := v_wph * 2;

  -- Deal `v_total` distinct words in random order.
  for i in 0 .. v_total - 1 loop
    v_word := (
      select w from unnest(v_bank) as w
      order by md5(w || p_game::text || i::text)
      offset i limit 1
    );
    insert into public.game_words (game_id, word_index, word)
    values (p_game, i, v_word);
  end loop;

  v_team := public.mw_starting_team(0);
  insert into public.game_state
    (game_id, phase, word_index, cluing_team, step, words_per_half, host_line)
  values
    (p_game, 'first_half', 0, v_team, 'awaiting_clue', v_wph,
     public.mw_clue_prompt(p_game, v_team, 'first_half'));

  return jsonb_build_object('ok', true);
end;
$$;

-- =============================================================================
-- Internal: the seat/role the current user may act as on the clock, or null.
-- Verifies the caller is the on-the-clock player for `p_expected_step`. The
-- host may also act for a computer (AI) seat so play never stalls.
-- =============================================================================
create or replace function public.mw_actor_ok(p_game uuid, p_role text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_profile uuid;
  v_is_ai   boolean;
  v_host    uuid;
begin
  select profile_id, is_ai into v_profile, v_is_ai
  from public.game_players
  where game_id = p_game and role = p_role;

  if v_profile = v_uid then
    return true;
  end if;

  -- Host may drive computer-filled seats.
  select host_id into v_host from public.games where id = p_game;
  return coalesce(v_is_ai, false) and v_host = v_uid;
end;
$$;

-- =============================================================================
-- Submit a one-word clue. Caller must be the on-the-clock clue-giver.
-- Returns: { ok } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_submit_clue(p_game uuid, p_text text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.game_state%rowtype;
  v_role text;
  v_name text;
  v_text text := btrim(p_text);
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;
  if v_text = '' then
    return jsonb_build_object('ok', false, 'reason', 'empty');
  end if;

  select * into s from public.game_state where game_id = p_game for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if s.phase not in ('first_half', 'second_half') or s.step <> 'awaiting_clue' then
    return jsonb_build_object('ok', false, 'reason', 'not_awaiting_clue');
  end if;

  v_role := public.mw_clue_giver_role(s.cluing_team, s.phase);
  if not public.mw_actor_ok(p_game, v_role) then
    return jsonb_build_object('ok', false, 'reason', 'not_your_turn');
  end if;

  select display_name into v_name
  from public.game_players where game_id = p_game and role = v_role;

  insert into public.game_plays
    (game_id, word_index, kind, team, role, player_name, text)
  values
    (p_game, s.word_index, 'clue', s.cluing_team, v_role,
     coalesce(v_name, 'Player ' || v_role), v_text);

  update public.game_state set
    step = 'awaiting_guess',
    pending_clue = v_text,
    host_line = (public.mw_guesser_role(s.cluing_team, s.phase)) ||
                ' — what is your guess?',
    updated_at = now()
  where game_id = p_game;

  return jsonb_build_object('ok', true);
end;
$$;

-- =============================================================================
-- Submit a guess. Caller must be the on-the-clock guesser. Resolves the word:
-- score on a match, steal to the other team on a miss, or auto-reveal once the
-- exchange limit is reached.
-- Returns: { ok, correct } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_submit_guess(p_game uuid, p_text text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.game_state%rowtype;
  v_role    text;
  v_name    text;
  v_word    text;
  v_text    text := btrim(p_text);
  v_correct boolean;
  v_value   int;
  v_used    int;
  v_next_team text;
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;
  if v_text = '' then
    return jsonb_build_object('ok', false, 'reason', 'empty');
  end if;

  select * into s from public.game_state where game_id = p_game for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if s.phase not in ('first_half', 'second_half') or s.step <> 'awaiting_guess' then
    return jsonb_build_object('ok', false, 'reason', 'not_awaiting_guess');
  end if;

  v_role := public.mw_guesser_role(s.cluing_team, s.phase);
  if not public.mw_actor_ok(p_game, v_role) then
    return jsonb_build_object('ok', false, 'reason', 'not_your_turn');
  end if;

  select word into v_word
  from public.game_words where game_id = p_game and word_index = s.word_index;

  select display_name into v_name
  from public.game_players where game_id = p_game and role = v_role;

  v_correct := public.mw_word_matches(v_text, v_word);

  insert into public.game_plays
    (game_id, word_index, kind, team, role, player_name, text, correct)
  values
    (p_game, s.word_index, 'guess', s.cluing_team, v_role,
     coalesce(v_name, 'Player ' || v_role), v_text, v_correct);

  if v_correct then
    v_value := public.mw_word_value(s.word_value, s.exchange_count);
    update public.game_state set
      score_a = score_a + case when s.cluing_team = 'A' then v_value else 0 end,
      score_b = score_b + case when s.cluing_team = 'B' then v_value else 0 end,
      step = 'resolved',
      pending_clue = null,
      last_outcome = 'guessed',
      host_line = 'Team ' || s.cluing_team || ' guessed "' || v_word ||
                  '"! +' || v_value || ' points.',
      updated_at = now()
    where game_id = p_game;
    return jsonb_build_object('ok', true, 'correct', true);
  end if;

  v_used := s.exchange_count + 1;
  if v_used >= s.max_exchanges then
    update public.game_state set
      exchange_count = v_used,
      step = 'resolved',
      pending_clue = null,
      last_outcome = 'revealed',
      host_line = 'Time''s up! The word was "' || v_word || '". No points.',
      updated_at = now()
    where game_id = p_game;
    return jsonb_build_object('ok', true, 'correct', false);
  end if;

  -- Steal: the other team gets a fresh clue for reduced value.
  v_next_team := case when s.cluing_team = 'A' then 'B' else 'A' end;
  update public.game_state set
    cluing_team = v_next_team,
    step = 'awaiting_clue',
    exchange_count = v_used,
    pending_clue = null,
    last_outcome = 'none',
    host_line = 'A steal! ' || public.mw_clue_prompt(p_game, v_next_team, s.phase),
    updated_at = now()
  where game_id = p_game;
  return jsonb_build_object('ok', true, 'correct', false);
end;
$$;

-- =============================================================================
-- Advance off the resolved beat to the next word, halftime, or game-over.
-- Any member may call it (or a client timer); a no-op unless step = 'resolved'.
-- Returns: { ok, phase }
-- =============================================================================
create or replace function public.mw_next_word(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.game_state%rowtype;
  v_next  int;
  v_total int;
  v_team  text;
  v_win   text;
begin
  if not public.mw_is_game_member(p_game) then
    return jsonb_build_object('ok', false, 'reason', 'not_member');
  end if;

  select * into s from public.game_state where game_id = p_game for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if s.step <> 'resolved' then
    return jsonb_build_object('ok', false, 'reason', 'not_resolved');
  end if;

  v_next  := s.word_index + 1;
  v_total := s.words_per_half * 2;

  if v_next >= v_total then
    v_win := case
      when s.score_a = s.score_b then null
      when s.score_a > s.score_b then 'A' else 'B' end;
    update public.game_state set
      phase = 'game_over',
      word_index = v_next,
      pending_clue = null,
      host_line = case
        when v_win is null then 'It''s a tie — what a game! ' ||
             s.score_a || ' to ' || s.score_b || '.'
        else 'Team ' || v_win || ' wins ' ||
             greatest(s.score_a, s.score_b) || ' to ' ||
             least(s.score_a, s.score_b) || '!' end,
      updated_at = now()
    where game_id = p_game;
    update public.games
      set status = 'finished', updated_at = now() where id = p_game;
    return jsonb_build_object('ok', true, 'phase', 'game_over');
  end if;

  if v_next = s.words_per_half then
    update public.game_state set
      phase = 'halftime',
      word_index = v_next,
      pending_clue = null,
      host_line = 'Halftime! Teams, switch clue-giver and guesser. Score: ' ||
                  s.score_a || ' – ' || s.score_b || '.',
      updated_at = now()
    where game_id = p_game;
    return jsonb_build_object('ok', true, 'phase', 'halftime');
  end if;

  v_team := public.mw_starting_team(v_next);
  update public.game_state set
    word_index = v_next,
    cluing_team = v_team,
    step = 'awaiting_clue',
    exchange_count = 0,
    pending_clue = null,
    last_outcome = 'none',
    host_line = public.mw_clue_prompt(p_game, v_team, s.phase),
    updated_at = now()
  where game_id = p_game;
  return jsonb_build_object('ok', true, 'phase', s.phase);
end;
$$;

-- =============================================================================
-- Leave halftime and deal the first word of the second half (roles switched).
-- Host only. Returns: { ok }
-- =============================================================================
create or replace function public.mw_begin_second_half(p_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s public.game_state%rowtype;
  v_host uuid;
  v_team text;
begin
  select host_id into v_host from public.games where id = p_game;
  if v_host is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if v_host <> auth.uid() then
    return jsonb_build_object('ok', false, 'reason', 'not_host');
  end if;

  select * into s from public.game_state where game_id = p_game for update;
  if not found or s.phase <> 'halftime' then
    return jsonb_build_object('ok', false, 'reason', 'not_halftime');
  end if;

  v_team := public.mw_starting_team(s.word_index);
  update public.game_state set
    phase = 'second_half',
    cluing_team = v_team,
    step = 'awaiting_clue',
    exchange_count = 0,
    pending_clue = null,
    last_outcome = 'none',
    host_line = public.mw_clue_prompt(p_game, v_team, 'second_half'),
    updated_at = now()
  where game_id = p_game;

  return jsonb_build_object('ok', true);
end;
$$;

-- =============================================================================
-- Row Level Security — SELECT only for members; writes via the functions above.
-- =============================================================================
alter table public.game_state enable row level security;
alter table public.game_words enable row level security;
alter table public.game_plays enable row level security;

drop policy if exists "game_state_select_member" on public.game_state;
create policy "game_state_select_member"
  on public.game_state for select
  using (public.mw_is_game_member(game_id));

drop policy if exists "game_words_select_member" on public.game_words;
create policy "game_words_select_member"
  on public.game_words for select
  using (public.mw_is_game_member(game_id));

drop policy if exists "game_plays_select_member" on public.game_plays;
create policy "game_plays_select_member"
  on public.game_plays for select
  using (public.mw_is_game_member(game_id));

-- Realtime: push live state + feed updates to seated players.
alter publication supabase_realtime add table public.game_state;
alter publication supabase_realtime add table public.game_plays;

-- Least-privilege execute grants.
grant execute on function public.mw_begin_play(uuid)            to authenticated;
grant execute on function public.mw_submit_clue(uuid, text)     to authenticated;
grant execute on function public.mw_submit_guess(uuid, text)    to authenticated;
grant execute on function public.mw_next_word(uuid)             to authenticated;
grant execute on function public.mw_begin_second_half(uuid)     to authenticated;


-- ============================================================================
-- 0008_join_preview.sql
-- ============================================================================
-- Match Word — Milestone 4 enhancement
-- "See who's already in the game before you join."
-- Run this in the Supabase SQL editor after 0007_gameplay.sql.
--
-- Why this is needed
-- ------------------
-- Joining by code used to seat the player immediately, so they only saw the
-- roster *after* landing in the room. Players want to confirm they're joining
-- the right game — and land on the same team as their friend — *before*
-- committing. This read-only function returns the current roster for a code
-- without seating anyone, so the client can show a preview + "Join" confirm.
--
-- It is SECURITY DEFINER (bypasses RLS) so a not-yet-member can read the seats
-- of a private game they hold the code for. It only ever reveals a game that is
-- still an open lobby, and returns just the display names, teams, and seats —
-- no profile ids or other personal data.

create or replace function public.mw_peek_game(p_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid     uuid := auth.uid();
  v_game    public.games%rowtype;
  v_players jsonb;
  v_taken   int;
  v_mine    boolean;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select * into v_game
  from public.games
  where code = p_code and status = 'lobby' and expires_at > now()
  order by created_at desc
  limit 1;

  if v_game.id is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  -- The seats, in play order, with only the safe-to-show fields.
  select
    coalesce(jsonb_agg(
      jsonb_build_object(
        'seat', gp.seat,
        'team', gp.team,
        'role', gp.role,
        'display_name', gp.display_name,
        'is_host', gp.is_host,
        'is_ai', gp.is_ai
      ) order by gp.seat
    ), '[]'::jsonb),
    count(*),
    bool_or(gp.profile_id = v_uid)
  into v_players, v_taken, v_mine
  from public.game_players gp
  where gp.game_id = v_game.id;

  return jsonb_build_object(
    'ok', true,
    'game_id', v_game.id,
    'code', v_game.code,
    'max_players', v_game.max_players,
    'seats_taken', v_taken,
    'already_member', coalesce(v_mine, false),
    'players', v_players
  );
end;
$$;

comment on function public.mw_peek_game(text) is
  'Read-only roster preview for a 4-digit code: returns the open lobby''s seats '
  '(names, teams, roles) without seating the caller, so the client can show a '
  '"who''s already here" confirm step before joining.';

grant execute on function public.mw_peek_game(text) to authenticated;


-- ============================================================================
-- 0009_quick_match_ai.sql
-- ============================================================================
-- Match Word — Milestone 4 enhancement
-- Quick match that always lands in a playable game, without shutting real
-- players out. Run this in the Supabase SQL editor after 0008_join_preview.sql.
--
-- Product goals (from the client)
-- -------------------------------
-- * Tapping "Find a Game" solo should match with other real players when a
--   lobby exists, and otherwise bring in computer players to fill the empty
--   spots so the person can start playing right away.
-- * Real-player matching must keep working: a game that was auto-filled with
--   computer players should still be joinable by a later human, who simply
--   takes over one of the computer seats.
--
-- How this works
-- --------------
-- * mw_seat_or_bump(): seats the caller in the lowest free seat; if the game is
--   full of computer players, the caller takes over the lowest computer seat
--   instead (the computer player steps aside). Returns the assigned seat, or -1
--   only when every seat is held by a human.
-- * mw_quick_match(): joins the oldest public lobby that has room for a human
--   (a free seat OR a computer seat to take over); if none exists, it creates a
--   new public game and fills the remaining seats with computer players so the
--   creator has a ready table. The new game stays public, so the next human to
--   quick-match will find it and take over a computer seat.
-- * mw_join_game(): now also uses mw_seat_or_bump, so a friend entering a code
--   can still get in (and land on a team) even if the host already filled the
--   empty seats with computer players.

-- =============================================================================
-- Seat the current user, taking over a computer seat if there's no free one.
-- Returns the assigned seat, or -1 when every seat is held by a human.
-- =============================================================================
create or replace function public.mw_seat_or_bump(p_game uuid)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_name  text;
  v_max   int;
  v_seat  int;
begin
  -- Already seated? Idempotent.
  select seat into v_seat
  from public.game_players
  where game_id = p_game and profile_id = v_uid;
  if v_seat is not null then
    return v_seat;
  end if;

  select max_players into v_max from public.games where id = p_game;
  select first_name into v_name from public.profiles where id = v_uid;

  -- Prefer the lowest free seat.
  select s.seat into v_seat
  from generate_series(0, v_max - 1) as s(seat)
  where not exists (
    select 1 from public.game_players gp
    where gp.game_id = p_game and gp.seat = s.seat
  )
  order by s.seat
  limit 1;

  if v_seat is not null then
    insert into public.game_players
      (game_id, profile_id, display_name, first_name, is_host, seat, team, role)
    values
      (p_game, v_uid, v_name, v_name, false, v_seat,
       public.mw_seat_team(v_seat), public.mw_seat_role(v_seat));
    return v_seat;
  end if;

  -- No free seat: take over the lowest computer seat.
  select seat into v_seat
  from public.game_players
  where game_id = p_game and is_ai
  order by seat
  limit 1;

  if v_seat is null then
    return -1;  -- Every seat is a human; genuinely full.
  end if;

  delete from public.game_players
  where game_id = p_game and seat = v_seat;

  insert into public.game_players
    (game_id, profile_id, display_name, first_name, is_host, seat, team, role)
  values
    (p_game, v_uid, v_name, v_name, false, v_seat,
     public.mw_seat_team(v_seat), public.mw_seat_role(v_seat));
  return v_seat;
end;
$$;

grant execute on function public.mw_seat_or_bump(uuid) to authenticated;

-- =============================================================================
-- Quick match: join the oldest open public lobby that has room for a human, or
-- create a new public game filled with computer players so play can start now.
-- Returns: { ok, game_id, matched }
-- =============================================================================
create or replace function public.mw_quick_match()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_game  uuid;
  v_seat  int;
  v_res   jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  -- Oldest public lobby the user can slot into: a free seat OR a computer seat
  -- to take over, and where they're not already seated.
  select g.id into v_game
  from public.games g
  where g.is_public
    and g.status = 'lobby'
    and g.expires_at > now()
    and not exists (
      select 1 from public.game_players gp
      where gp.game_id = g.id and gp.profile_id = v_uid
    )
    and (
      (select count(*) from public.game_players gp where gp.game_id = g.id)
        < g.max_players
      or exists (
        select 1 from public.game_players gp
        where gp.game_id = g.id and gp.is_ai
      )
    )
  order by g.created_at asc
  limit 1;

  if v_game is not null then
    v_seat := public.mw_seat_or_bump(v_game);
    if v_seat >= 0 then
      return jsonb_build_object('ok', true, 'game_id', v_game, 'matched', true);
    end if;
    -- Raced and lost the last opening; fall through to a fresh game.
  end if;

  -- No match: create a new public game and fill the rest with computer players.
  v_res  := public.mw_create_game(true);
  v_game := (v_res ->> 'game_id')::uuid;
  perform public.mw_fill_seats(v_game);
  return jsonb_build_object('ok', true, 'game_id', v_game, 'matched', false);
end;
$$;

-- =============================================================================
-- Join by code — now takes over a computer seat if the lobby was pre-filled, so
-- a friend can always get in (and see which team they're on via mw_peek_game).
-- Returns: { ok, game_id } or { ok:false, reason }
-- =============================================================================
create or replace function public.mw_join_game(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_game  uuid;
  v_seat  int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select id into v_game
  from public.games
  where code = p_code and status = 'lobby' and expires_at > now()
  order by created_at desc
  limit 1;

  if v_game is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  v_seat := public.mw_seat_or_bump(v_game);
  if v_seat < 0 then
    return jsonb_build_object('ok', false, 'reason', 'full');
  end if;

  return jsonb_build_object('ok', true, 'game_id', v_game);
end;
$$;


-- ============================================================================
-- 0010_join_seat.sql
-- ============================================================================
-- Match Word — Milestone 4 enhancement
-- "Pick your own seat (and team) in the join preview."
-- Run this in the Supabase SQL editor after 0009_quick_match_ai.sql.
--
-- Why this is needed
-- ------------------
-- The join preview (mw_peek_game) lets a player see who's already in a game
-- before committing. Players then asked to *choose* which seat they take, so a
-- friend can deliberately land on the same team (even seats = Team A, odd
-- seats = Team B). This function seats the caller in a specific seat they
-- tapped, instead of the automatic "lowest free seat" rule.
--
-- Rules
-- -----
-- * A free seat is taken directly.
-- * A seat held by a computer player is taken over (the computer steps aside),
--   just like mw_seat_or_bump — so pre-filled games stay pickable.
-- * A seat held by another human is refused ('seat_taken') so two people can't
--   collide on the same chair.
-- * If the caller is already seated elsewhere in this game, they're moved to
--   the chosen seat (team/role updated to match the new seat).
--
-- SECURITY DEFINER so a not-yet-member holding the code can seat themselves.

create or replace function public.mw_join_seat(p_code text, p_seat int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid       uuid := auth.uid();
  v_game      public.games%rowtype;
  v_name      text;
  v_occupant  public.game_players%rowtype;
  v_mine      int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  select * into v_game
  from public.games
  where code = p_code and status = 'lobby' and expires_at > now()
  order by created_at desc
  limit 1;

  if v_game.id is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  if p_seat < 0 or p_seat >= v_game.max_players then
    return jsonb_build_object('ok', false, 'reason', 'bad_seat');
  end if;

  select first_name into v_name from public.profiles where id = v_uid;

  -- Who (if anyone) currently holds the chosen seat?
  select * into v_occupant
  from public.game_players
  where game_id = v_game.id and seat = p_seat;

  -- A human already sitting there (and it isn't us) blocks the pick.
  if v_occupant.profile_id is not null
     and not v_occupant.is_ai
     and v_occupant.profile_id <> v_uid then
    return jsonb_build_object('ok', false, 'reason', 'seat_taken');
  end if;

  -- Already sitting in the chosen seat? Idempotent success.
  if v_occupant.profile_id = v_uid then
    return jsonb_build_object('ok', true, 'game_id', v_game.id, 'seat', p_seat);
  end if;

  -- Free the chosen seat if a computer player is holding it.
  if v_occupant.seat is not null then
    delete from public.game_players
    where game_id = v_game.id and seat = p_seat;
  end if;

  -- If we were already seated elsewhere in this game, vacate that seat.
  select seat into v_mine
  from public.game_players
  where game_id = v_game.id and profile_id = v_uid;
  if v_mine is not null then
    delete from public.game_players
    where game_id = v_game.id and profile_id = v_uid;
  end if;

  insert into public.game_players
    (game_id, profile_id, display_name, first_name, is_host, seat, team, role)
  values
    (v_game.id, v_uid, v_name, v_name, false, p_seat,
     public.mw_seat_team(p_seat), public.mw_seat_role(p_seat));

  return jsonb_build_object('ok', true, 'game_id', v_game.id, 'seat', p_seat);
end;
$$;

comment on function public.mw_join_seat(text, int) is
  'Seats the caller in a specific chosen seat of an open lobby (taking over a '
  'computer seat if needed), so players can pick their own team in the join '
  'preview. Refuses a seat already held by another human.';

grant execute on function public.mw_join_seat(text, int) to authenticated;


-- ============================================================================
-- 0011_quick_match_wait.sql
-- ============================================================================
-- Match Word — Milestone 4 enhancement
-- "Give real players a moment before the studio players fill in."
-- Run this in the Supabase SQL editor after 0010_join_seat.sql.
--
-- Why this changes
-- ----------------
-- 0009's mw_quick_match filled the empty seats with studio (AI) players
-- IMMEDIATELY when it created a fresh game, so a solo player never had a window
-- for a real person to join first. The client now wants a short, adjustable
-- "looking for players" wait before the studio players step in — so real
-- matches get first chance at the open seats.
--
-- The wait itself is timed on the CLIENT (LobbyController.quickMatchFillDelay),
-- which calls mw_fill_seats when it elapses (and only if seats are still open).
-- So this migration's job is simply to STOP mw_quick_match from auto-filling on
-- create; everything else about matching/seat-bumping is unchanged.
--
-- Returns: { ok, game_id, matched }
--   matched=true  -> slotted into an existing public lobby
--   matched=false -> created a fresh public game (seats left open for the wait)

create or replace function public.mw_quick_match()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_game  uuid;
  v_seat  int;
  v_res   jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_signed_in');
  end if;

  -- Oldest public lobby the user can slot into: a free seat OR a computer seat
  -- to take over, and where they're not already seated.
  select g.id into v_game
  from public.games g
  where g.is_public
    and g.status = 'lobby'
    and g.expires_at > now()
    and not exists (
      select 1 from public.game_players gp
      where gp.game_id = g.id and gp.profile_id = v_uid
    )
    and (
      (select count(*) from public.game_players gp where gp.game_id = g.id)
        < g.max_players
      or exists (
        select 1 from public.game_players gp
        where gp.game_id = g.id and gp.is_ai
      )
    )
  order by g.created_at asc
  limit 1;

  if v_game is not null then
    v_seat := public.mw_seat_or_bump(v_game);
    if v_seat >= 0 then
      return jsonb_build_object('ok', true, 'game_id', v_game, 'matched', true);
    end if;
    -- Raced and lost the last opening; fall through to a fresh game.
  end if;

  -- No match: create a fresh public game and LEAVE the seats open. The client
  -- waits quickMatchFillDelay for real players, then calls mw_fill_seats if the
  -- seats are still empty. The game stays public, so other humans quick-matching
  -- during the wait will find it and take a seat first.
  v_res  := public.mw_create_game(true);
  v_game := (v_res ->> 'game_id')::uuid;
  return jsonb_build_object('ok', true, 'game_id', v_game, 'matched', false);
end;
$$;

comment on function public.mw_quick_match() is
  'Quick match: slot into an open public lobby (free or take-over-AI seat), or '
  'create a fresh public game with seats left OPEN. The client waits a short, '
  'adjustable window for real players before calling mw_fill_seats.';


-- ============================================================================
-- 0012_character_accessories.sql
-- ============================================================================
-- Match Word — Milestone 3 (rebuild) schema
-- Character Creation now uses the artist's real art with new accessory layers:
--   hat        — headwear (cap / knit / brim / sun hat)
--   earrings   — jewellery
--   accessory  — a held item (bag / walking cane / walker)
-- Run this in the Supabase SQL editor after 0002_characters.sql.
--
-- The older colour/eyes columns (base_color, hair_color, eyes, eye_color) are
-- left in place for backward compatibility; the rebuilt builder no longer
-- writes to them (the real art is full-colour, so there is nothing to tint).

alter table public.characters add column if not exists hat        text;
alter table public.characters add column if not exists earrings   text;
alter table public.characters add column if not exists accessory  text;

comment on column public.characters.hat is
  'Headwear option id (cap / knit / brim / sun hat), or null for none.';
comment on column public.characters.earrings is
  'Earrings option id, or null for none.';
comment on column public.characters.accessory is
  'Held-item option id (bag / cane / walker), or null for none.';



-- ============================================================================
-- 0013_game_characters.sql
-- ============================================================================
-- "Show each player's saved character on the game-show stage."
-- Run this in the Supabase SQL editor after 0012_character_accessories.sql.
--
-- Why this is needed
-- ------------------
-- The `characters` table has strict RLS: a player may only read their OWN row
-- (`auth.uid() = profile_id`). That is correct for privacy, but it means the
-- live game screen could not read the OTHER seated players' characters, so the
-- studio podiums fell back to a generic clay bust for everyone. This function
-- lets any player who is a member of a game read the (non-sensitive, cosmetic)
-- character of everyone seated in THAT game — and nothing else.
--
-- It returns only the cosmetic layer ids + display name/role/seat, never any
-- private data. Computer-filled seats (profile_id null) simply have no row here;
-- the client generates a friendly look for them locally.

create or replace function public.mw_game_characters(p_game uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'role',         gp.role,
        'seat',         gp.seat,
        'display_name', gp.display_name,
        'base',         c.base,
        'hair',         c.hair,
        'outfit',       c.outfit,
        'glasses',      c.glasses,
        'hat',          c.hat,
        'earrings',     c.earrings,
        'accessory',    c.accessory
      ) order by gp.seat
    ),
    '[]'::jsonb
  )
  from public.game_players gp
  join public.characters c on c.profile_id = gp.profile_id
  where gp.game_id = p_game
    and gp.profile_id is not null
    -- Only members of the game may read its roster of characters.
    and public.mw_is_game_member(p_game);
$$;

comment on function public.mw_game_characters(uuid) is
  'Cosmetic character layers (base/hair/outfit/glasses/hat/earrings/accessory) '
  'for every seated human in a game the caller belongs to, so the live stage '
  'can render each player''s saved character. Members-only; returns no private '
  'data. Computer seats have no row (the client draws them locally).';

grant execute on function public.mw_game_characters(uuid) to authenticated;


-- ============================================================================
-- 0028_onboarding_seen.sql
-- ============================================================================
alter table public.profiles
  add column if not exists onboarding_seen boolean not null default false;

comment on column public.profiles.onboarding_seen is
  'True after the player finishes or skips the first-launch walkthrough.';


-- ============================================================================
-- 0029_subscription_product_699.sql
-- ============================================================================
alter table public.subscriptions
  alter column product_id set default 'matchword_monthly_699';

comment on column public.subscriptions.product_id is
  'Store product. Current paid plan: matchword_monthly_699 ($6.99 CAD/mo).';


-- ============================================================================
-- 0030_device_trials_ip.sql
-- ============================================================================
create unique index if not exists device_trials_ip_address_uidx
  on public.device_trials (ip_address)
  where ip_address is not null;

comment on table public.device_trials is
  'One free trial per device_id and per ip_address. Written by claim-trial Edge Function.';
