import 'dart:math' as math;

import 'package:flutter/material.dart';

/// A gentle, looping "idle" motion for a character figure (Milestone 7).
///
/// Soft breathing scale + slow sway so a static figure feels alive. Named pose
/// frames (tongue / worry / smug / shrug / hairfix / selfie) are applied by
/// [IdleCharacterPreview] in the character feature, which swaps the base layer
/// for pose PNGs generated by `tools/generate_idle_poses.py`.
///
/// Motion is deliberately subtle and slow so it reads as calm and premium.
class IdleAnimation extends StatefulWidget {
  const IdleAnimation({
    super.key,
    required this.child,
    this.enabled = true,
    this.period = const Duration(seconds: 4),
    this.intensity = 1.0,
  });

  final Widget child;

  /// When false the child is shown perfectly still.
  final bool enabled;

  /// One full breathe-in/out cycle.
  final Duration period;

  /// Scales the motion. 1.0 is the default subtle amount.
  final double intensity;

  @override
  State<IdleAnimation> createState() => _IdleAnimationState();
}

class _IdleAnimationState extends State<IdleAnimation>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    vsync: this,
    duration: widget.period,
  );

  @override
  void initState() {
    super.initState();
    if (widget.enabled) _controller.repeat();
  }

  @override
  void didUpdateWidget(covariant IdleAnimation oldWidget) {
    super.didUpdateWidget(oldWidget);
    _controller.duration = widget.period;
    if (widget.enabled && !_controller.isAnimating) {
      _controller.repeat();
    } else if (!widget.enabled && _controller.isAnimating) {
      _controller.stop();
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!widget.enabled) return widget.child;
    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) {
        final t = _controller.value * 2 * math.pi;
        final breathe = 1 + 0.015 * widget.intensity * math.sin(t);
        final sway = 0.012 * widget.intensity * math.sin(t + math.pi / 3);
        return Transform.rotate(
          angle: sway,
          child: Transform.scale(
            scale: breathe,
            alignment: Alignment.bottomCenter,
            child: child,
          ),
        );
      },
      child: widget.child,
    );
  }
}
